import {$,$$,api,esc,uid,getDraft,queueDraft,busy,feedbackHTML,toast} from './core.js';
import {speak,voice,stopAudio} from './audio.js';
const parse=raw=>{try{return JSON.parse(typeof raw==='string'?raw:raw?.text||'null');}catch{return null;}};
const mounts=new WeakMap();
function validSession(session,id,scenarioID){return session?.version===1&&session.id===id&&session.scenarioId===scenarioID&&Array.isArray(session.turns)&&session.turns.length<=6&&session.turns.every(t=>typeof t.id==='string'&&typeof t.answer==='string'&&typeof t.reply==='string'&&['writing','speaking'].includes(t.mode));}
export async function mountConversation(root,data,refresh,scenarioID='',sessionID=''){
 mounts.get(root)?.dispose?.();const route=location.hash,token={};mounts.set(root,token);let drawVersion=0;
 const current=()=>mounts.get(root)===token&&root.isConnected&&location.hash===route;
 const dispose=()=>{stopAudio();window.removeEventListener('hashchange',dispose);};token.dispose=dispose;window.addEventListener('hashchange',dispose,{once:true});
 stopAudio();
 root.innerHTML='<p class="small-note">Открываем разговорную практику…</p>';
 const catalog=await api('/conversation/scenarios');if(!current())return;
 const scenario=catalog.scenarios.find(s=>s.id===scenarioID);
 if(!scenario){
  const saved=Object.entries(data.state.drafts||{}).filter(([k])=>k.startsWith('conversation:v1:')).map(([,v])=>parse(v)).filter(s=>validSession(s,s?.id,s?.scenarioId)).reverse();
  root.innerHTML=`<header class="page-head"><div><span class="eyebrow">ОТВЕТ ЗАВИСИТ ОТ ТЕБЯ</span><h1>Разговорная практика</h1><p class="small-note">Собеседник отвечает на твою мысль, уточняет и возражает. Шесть твоих реплик, затем разбор. Можно говорить голосом или сначала отрепетировать письменно.</p></div></header><div class="mastery-grid">${catalog.scenarios.map(s=>`<article class="mastery-card"><span class="eyebrow">${esc(s.level)} · AMERICAN ENGLISH</span><h2>${esc(s.title)}</h2><p>${esc(s.goal)}</p><a class="btn" href="#/conversation/${s.id}/${uid()}">Начать разговор →</a></article>`).join('')}</div>${saved.length?`<h2 style="margin-top:32px">Сохранённые разговоры</h2><div class="mastery-links">${saved.slice(0,30).map(s=>`<a href="#/conversation/${encodeURIComponent(s.scenarioId)}/${encodeURIComponent(s.id)}">${esc(catalog.scenarios.find(x=>x.id===s.scenarioId)?.title||s.scenarioId)} · ${s.turns.length} реплик →</a>`).join('')}</div>`:''}<p class="small-note" style="margin-top:28px">Разговор использует помощника из настроек. Записи реплик и разбор сохраняются на этом компьютере. Расшифровка помогает работать над языком; оценка акустического произношения сюда не входит.</p>`;return;
 }
 if(!sessionID){location.hash='/conversation/'+scenario.id+'/'+uid();return;}
 if(!/^[A-Za-z0-9_-]{1,100}$/.test(sessionID))throw Error('Некорректный идентификатор разговора');
 let session=parse(data.state.drafts?.['conversation:v1:'+sessionID])||{version:1,id:sessionID,scenarioId:scenario.id,turns:[]},mode='writing',nonce=uid(),sending=false;
 if(!validSession(session,sessionID,scenario.id))throw Error('Сохранённый разговор относится к другому сценарию или содержит неполные данные');
 const key=()=>`conversation:answer:${sessionID}:${session.turns.length}`;
 function draw(){
  if(!current())return;stopAudio();
  const version=++drawVersion,own=()=>current()&&drawVersion===version;
  const finished=session.turns.length>=catalog.maxTurns;
  root.innerHTML=`<div class="conversation-page"><a class="small-note" href="#/conversation">← Все разговоры</a><header class="page-head"><div><span class="eyebrow">${esc(scenario.level)} · ${session.turns.length} / ${catalog.maxTurns} ТВОИХ РЕПЛИК</span><h1>${esc(scenario.title)}</h1><p>${esc(scenario.goal)}</p></div></header><section class="conversation-log" aria-label="История разговора"><article class="conversation-partner"><span>Собеседник</span><p lang="en">${esc(scenario.opening)}</p><button class="btn small ghost" data-conversation-play="-1">Послушать</button></article>${session.turns.map((t,i)=>`<article class="conversation-learner"><span>Ты · ${t.mode==='speaking'?'расшифровка голоса':'письменная репетиция'}</span><p lang="en">${esc(t.answer)}</p></article><article class="conversation-partner"><span>Собеседник</span><p lang="en">${esc(t.reply)}</p><button class="btn small ghost" data-conversation-play="${i}">Послушать</button></article>`).join('')}</section>${!finished?`<section class="card conversation-compose"><label for="conversation-answer">Твоя следующая реплика</label><textarea id="conversation-answer" rows="4" maxlength="1800" spellcheck="false">${esc(getDraft(key(),data.state))}</textarea><p class="small-note">Можно попросить собеседника повторить, уточнить значение или объяснить проще — прямо на английском.</p><div class="actions"><button id="conversation-voice" class="btn">Ответить голосом</button><button id="conversation-send" class="btn primary">Отправить реплику →</button></div><audio id="audio-preview" class="audio-preview" controls hidden></audio></section>`:'<p class="small-note">Раунд завершён. Посмотри, удалось ли достичь цели разговора, затем разбери формулировки.</p>'}${session.turns.length?'<section class="card conversation-review"><h2>Что получилось выразить</h2><p class="small-note">Разберём твои реплики: смысл, грамматику, сочетания и уместность. Другие корректные решения принимаются.</p><button id="conversation-review" class="btn">Разобрать мои реплики</button><div id="conversation-feedback"></div><a class="btn small ghost" href="#/notebook">Сохранить полезную формулировку в «Мои мысли»</a></section>':''}</div>`;
  $$('[data-conversation-play]',root).forEach(b=>b.onclick=()=>speak(+b.dataset.conversationPlay===-1?scenario.opening:session.turns[+b.dataset.conversationPlay].reply));
  if(!finished){const input=$('#conversation-answer',root),answerKey=key(),modeKey=`conversation:mode:${sessionID}:${session.turns.length}`,storedMode=parse(getDraft(modeKey,data.state));mode=storedMode?.answer===input.value&&storedMode.mode==='speaking'?'speaking':'writing';
   const changed=()=>{nonce=uid();queueDraft(answerKey,input.value);queueDraft(modeKey,JSON.stringify({answer:input.value,mode}));};input.oninput=()=>{mode='writing';changed();};$('#conversation-voice',root).onclick=e=>voice(e.currentTarget,input,data.settings,()=>{if(own()){mode='speaking';changed();}});
   $('#conversation-send',root).onclick=e=>busy(e.currentTarget,async()=>{if(sending)return;stopAudio();if(input.value.trim().length<2)throw Error('Сначала сформулируй ответ');sending=true;const submitted=input.value,payload={id:sessionID,requestID:nonce,scenarioID:scenario.id,answer:submitted,mode,expectedTurns:session.turns.length};input.disabled=true;$('#conversation-voice',root).disabled=true;
    try{await queueDraft(answerKey,submitted,true);await queueDraft(modeKey,JSON.stringify({answer:submitted,mode:payload.mode}),true);const result=await api('/conversation/turn',payload);if(!validSession(result,sessionID,scenario.id))throw Error('Сервер вернул неполный разговор; открой сохранённую версию.');session=result;data={...data,state:{...data.state,drafts:{...data.state.drafts,['conversation:v1:'+sessionID]:{text:JSON.stringify(result)}}}};try{const updated=await refresh(),fresh=parse(updated.state.drafts?.['conversation:v1:'+sessionID]);if(validSession(fresh,sessionID,scenario.id)&&fresh.turns.length>=result.turns.length&&result.turns.every((t,i)=>fresh.turns[i]?.id===t.id))session=fresh;data={...updated,state:{...updated.state,drafts:{...updated.state.drafts,['conversation:v1:'+sessionID]:{text:JSON.stringify(session)}}}};}catch(error){if(own())toast('Реплика сохранена. Обновить остальные данные не удалось: '+error.message,true);}nonce=uid();mode='writing';if(own()){draw();$('.conversation-compose',root)?.scrollIntoView({block:'nearest',behavior:'smooth'});}}
    finally{sending=false;if(own()&&input.isConnected){input.disabled=false;$('#conversation-voice',root).disabled=false;}}},'Собеседник отвечает…');
  }
  if(session.turns.length){const count=session.turns.length,exerciseId=sessionID+'-'+count,legacyId='conversation-'+exerciseId,latest=(data.state.attempts||[]).filter(a=>(a.lessonId==='conversation'&&a.exerciseId===exerciseId)||(a.lessonId==='free'&&a.exerciseId===legacyId)).at(-1);if(latest)$('#conversation-feedback',root).innerHTML=feedbackHTML(latest);
   const reviewKey=`conversation:review-request:${sessionID}:${count}:${data.settings.provider||'offline'}`;let reviewID=getDraft(reviewKey,data.state)||uid();
   const reviewAnswer=session.turns.map((t,i)=>`${i+1}. ${t.answer}`).join('\n'),reviewMode=session.turns.every(t=>t.mode==='speaking')?'speaking':'writing';
   $('#conversation-review',root).onclick=e=>busy(e.currentTarget,async()=>{await queueDraft(reviewKey,reviewID,true);const response=await api('/check',{id:reviewID,lessonId:'conversation',exerciseId,mode:reviewMode,level:scenario.level,answer:reviewAnswer});data={...data,state:{...data.state,attempts:[...(data.state.attempts||[]).filter(a=>a.id!==response.id),response]}};try{data=await refresh();}catch(error){if(own())toast('Разбор сохранён. Обновить остальные данные не удалось: '+error.message,true);}if(own())$('#conversation-feedback',root).innerHTML=feedbackHTML(response);},'Разбираем разговор…');
  }
 }
 draw();
}
