import {syncSelect} from './select-control.js';
import {$,$$,esc,icon,api,busy,toast,progressLesson,getDraft,localDraft,queueDraft,words,feedbackHTML,bindMistakes,uid} from './core.js';
import {voice,stopAudio} from './audio.js';
import {loadBookStatus} from './book-reader.js';
import {loadCurriculumCoverage,mountCurriculumCoverage} from './curriculum-coverage.js';
import {lessonSequence,lessonSourceRelations,lessonRouteInfo} from './lesson-sequence.js';
import {russianCount,russianPlural} from './russian-count.js';
import {bookIntakeNotice} from './book-intake.js';
const levels=['A1','A2','B1','B2','C1','C2'];
const bookHues=[221,265,152,23,204,350,40,183,276,20];
const lessonNouns=['занятие','занятия','занятий'];
const bookReadyRatio=(ready,total)=>`<b>${esc(ready)}</b><span> / ${esc(total)}</span>`;
export function includesLevel(value,level){
 const bounds=(String(value).match(/[ABC][12]/g)||[]).map(v=>levels.indexOf(v));
 return bounds.length>0&&levels.indexOf(level)>=Math.min(...bounds)&&levels.indexOf(level)<=Math.max(...bounds);
}
export function roadmapLessons(lessons,path,level,query='',allLevels=false,studyRoute=null){
 const q=query.trim().toLowerCase();
 return lessonSequence(lessons,path).filter(({lesson:l,level:home})=>!l.id.startsWith('cinema-')&&lessonRouteInfo(l.id,studyRoute).introduction&&(allLevels||home===level)&&(!q||[l.title,l.subtitle,l.goal,l.group,l.formula].join(' ').toLowerCase().includes(q))).map(record=>record.lesson);
}
// Group only neighboring steps: collecting every matching category globally
// would move later deepening/capstone work ahead of its planned prerequisites.
export function roadmapLessonGroups(lessons){
 const groups=[];
 for(const lesson of lessons){
  const title=lesson.id==='path-c2-capstone'?'Итоговая мастерская C2':['Произношение и слушание','Произношение и слух'].includes(lesson.group)?'Произношение и аудирование':lesson.group||'Практика';
  let group=groups.at(-1);if(!group||group.title!==title){group={title,lessons:[]};groups.push(group);}
  group.lessons.push(lesson);
 }
 return groups;
}
export function libraryUnitMatches(book,unit,query){
 const q=query.trim().toLowerCase();
 if(/^\d+$/.test(q))return unit.unit===Number(q);
 return !q||[unit.title,unit.titleRu,unit.category,book.title].join(' ').toLowerCase().includes(q);
}
export function readLibraryUnits(books,read={}){
 const result=new Set();
 for(const book of books)for(const unit of book.units){
  const id=unit.equivalentUnitId||unit.id;
  if(read[unit.id]||read[id]||read['book-'+unit.id]||read['book-'+id])result.add(id);
 }
 return result;
}
export function libraryUnitStatus(unit,status,read,level){
 const id=unit.equivalentUnitId||unit.id;
 if(read.has(id))return {label:'Прочитано',tone:'green'};
 if(status?.units?.[id]?.status==='ready')return {label:'Урок готов',tone:'blue'};
 return {label:level,tone:''};
}
function utf8Clip(text,maxBytes){
 const encoder=new TextEncoder();if(encoder.encode(text).length<=maxBytes)return text;
 let result='',bytes=0;for(const char of text){const size=encoder.encode(char).length;if(bytes+size>maxBytes)break;result+=char;bytes+=size;}return result;
}
export function unitCheckContext(source,notes){
 // The API limit is UTF-8 bytes. Reserve room for the learner's notes even
 // when the original two-page unit is long or the notes contain Cyrillic.
 const note=String(notes||'').trim(),base=utf8Clip(String(source),note?11000:15500);
 return utf8Clip(base+(note?'\nLearner notes (untrusted study data):\n'+utf8Clip(note,4500):''),15900);
}
const heading=(title,sub,extra='')=>`<div class="page-head"><div><div class="eyebrow">ENGLISH / A1 → C2</div><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`;
const objectives={A1:'Собрать простое предложение и рассказать о себе.',A2:'Описать опыт, планы и бытовую ситуацию.',B1:'Поддержать разговор и связно объяснить свою мысль.',B2:'Уверенно обсуждать, аргументировать и понимать естественную речь.',C1:'Работать с нюансами, сложными текстами и разными регистрами.',C2:'Точно передавать оттенки смысла, синтезировать и редактировать.'};
export function roadmapLessonHTML(l,state,home,relations=[],deepening=null){const p=progressLesson(l,state),sources=lessonSourceRelations(l.id,relations);return `<div class="path-lesson-row"><a class="path-lesson" href="#/lesson/${esc(l.id)}"><span class="path-check">${p.done?icon('check'):icon(l.exercises.some(e=>e.kind==='speak')?'mic':'book')}</span><div><h3>${esc(l.title)}</h3><p>${esc(l.goal)}</p></div><span class="path-lesson-meta" title="Место занятия в программе">${esc(home||l.level)}<small>${p.tried}/${p.total} · ${l.minutes}′</small></span>${icon('arrow')}</a>${deepening?`<div class="path-source-relations"><strong>Углубление темы</strong><p>${esc(deepening.reason)}</p><p>Опора перед занятием: <a href="#/lesson/${esc(deepening.afterLessonId)}">${esc(deepening.afterTitle||deepening.afterLessonId)}</a>. Здесь нужны отдельные собственные ответы.</p></div>`:''}${sources.length?`<details class="path-source-relations"><summary>Другие источники по теме · ${sources.length}</summary><p>Другое объяснение, дополнительные упражнения и нюансы этой темы.</p><ul>${sources.map(source=>`<li><span>${source.relation==='alternative'?'Альтернатива':'Связанный материал'}:</span> <a href="${esc(source.href)}">${esc(source.title)}</a></li>`).join('')}</ul></details>`:''}</div>`;}
export function mountRoadmap(root,data,initial,{sourceRelations=null}={}){
 const primary=(level=null,query='',allLevels=false)=>roadmapLessons(data.lessons,data.learningPath,level,query,allLevels,data.studyRoute);
 const catalog=data.library?.books||[],units=catalog.filter(b=>!b.duplicateOf).reduce((n,b)=>n+b.units.length,0),course=primary(null,'',true),done=course.filter(l=>progressLesson(l,data.state).done).length;
 const preferred=initial||getDraft('roadmap-level',data.state)||'B1';
 let selected=levels.includes(preferred)?preferred:'B1',query='',coverageLevel;
 root.innerHTML=heading('От первого предложения<br>до точности мысли.','Весь маршрут открыт. Каждое занятие занимает одно место в последовательности A1–C2; к пройденному можно вернуться для повторения.',`<a class="btn" href="#/tenses">${icon('clock')} Карта времён</a>`)+`
 <div class="path-summary"><div><strong id="path-main-count">${course.length}</strong><span id="path-main-label">${russianPlural(course.length,lessonNouns)} основной программы</span></div><div><strong id="path-task-count">${course.reduce((n,l)=>n+l.exercises.length,0)}</strong><span id="path-task-label">${russianPlural(course.reduce((n,l)=>n+l.exercises.length,0),['задание','задания','заданий'])} со своим ответом</span></div><div><strong id="path-book-ready" class="path-book-ratio">${bookReadyRatio('…',units)}</strong><span>книжных уроков готовы · <a href="#/books">открыть</a></span></div><div><strong id="path-done-count">${done}</strong><span id="path-done-label">${russianPlural(done,lessonNouns)} пройдено</span></div></div>
 <div class="level-rail" role="group" aria-label="Выбор уровня">${levels.map((level,i)=>{const ls=primary(level);return `<button data-level="${level}" aria-pressed="false"><span>0${i+1}</span><strong>${level}</strong><small data-level-count="${level}">${russianCount(ls.length,lessonNouns)}</small></button>`;}).join('')}</div>
 <section class="level-focus" id="level-focus"></section>
 <section id="path-coverage" aria-label="Сверка программы и новые материалы"></section>
 <div class="path-tabs"><button class="active" data-path-tab="lessons">Готовые занятия</button><button data-path-tab="plan">Ритм и контрольные точки</button><a href="#/pronunciation">Чтение и произношение ${icon('sound')}</a><a href="#/coverage">Карта навыков ${icon('arrow')}</a><a href="#/books">Все оглавления ${icon('arrow')}</a><a href="#/cinema">Киноклуб ${icon('arrow')}</a></div>
 <section id="path-lessons"><div class="filters"><div class="search">${icon('search')}<input id="lesson-search" aria-label="Найти занятие" placeholder="Найти тему, навык или конструкцию…"></div><label class="small-note"><input id="all-levels" type="checkbox"> Искать на всех уровнях</label></div><div id="path-list"></div><div id="path-overviews"></div></section>
 <section id="path-plan" hidden><div class="weekly-plan">${[['01','Сначала вспомнить','10–15 минут. Ответь по-английски на русскую сторону карточек. Вернись к двум ошибкам прошлого занятия.'],['02','Понять и применить','30–40 минут. Один урок или юнит книги. Свои примеры → проверка → переписанный ответ.'],['03','Услышать и пересказать','25–35 минут. Сцена или запись. Первый просмотр без субтитров, второй — с разбором, затем пересказ.'],['04','Поговорить','20–30 минут. Монолог, возражение или ролевая беседа. Прослушай запись, исправь формулировки, запиши ещё раз.'],['05','Написать','25–40 минут. Текст с целью и адресатом. Сохрани первую и исправленную версии; выбери 3–5 полезных фраз.'],['06','Проверить перенос','Раз в неделю: новый текст, незнакомая запись, письменная работа и устный ответ без конспекта. Затем повтор проблемных тем.']].map(([n,t,s])=>`<article class="surface"><span class="eyebrow">ШАГ ${n}</span><h3>${t}</h3><p>${s}</p></article>`).join('')}</div><div class="notice">Прохождение уроков показывает выполненную практику. Уровень проверяй на незнакомом материале: чтение, аудирование, письмо, устная речь и взаимодействие. Для C1–C2 нужны разные акценты, жанры, аудитории и регулярная внешняя обратная связь.</div></section>`;
 const bookCount=$('#path-book-ready',root);
 $('#path-coverage',root).insertAdjacentHTML('beforebegin','<section class="notice small-note" id="path-book-intake" aria-label="Готовность новых учебников">Проверяем новые учебники…</section>');
 api('/library/status').then(status=>{if(!bookCount.isConnected)return;const ids=new Set(catalog.filter(b=>!b.duplicateOf).flatMap(b=>b.units.map(u=>u.equivalentUnitId||u.id)));const ready=[...ids].filter(id=>status.units?.[id]?.status==='ready').length;bookCount.innerHTML=bookReadyRatio(status.ready??ready,status.total??units);$('#path-book-intake',root).innerHTML=bookIntakeNotice(status,units);}).catch(()=>{if(bookCount.isConnected){bookCount.innerHTML=bookReadyRatio('—',units);$('#path-book-intake',root).innerHTML=bookIntakeNotice(null,units);}});
 const weekly=data.learningPath?.weeklyPlan||[],skillMap=data.learningPath?.skills||[];
 if(weekly.length)$('#path-plan',root).insertAdjacentHTML('afterbegin',`<div class="section-heading"><h2>Неделя с английским</h2><span class="small-note">Базовый ритм · около 2 часов в день</span></div><div class="week-calendar">${weekly.map((d,i)=>`<details class="surface" ${i===((new Date().getDay()+6)%7)?'open':''}><summary><span class="eyebrow">${esc(d.day)} / ${d.minutes} МИН</span><strong>${esc(d.title)}</strong></summary><ol>${d.blocks.map(b=>`<li><span>${esc(b.title)}</span><small>${b.minutes}′</small></li>`).join('')}</ol></details>`).join('')}</div><div class="section-heading"><h2>Что именно развивать</h2></div><div class="skill-map">${skillMap.map(s=>`<details class="surface"><summary>${esc(s.title)}</summary><p>${esc(s.goal)}</p><small>${esc(s.evidence)}</small></details>`).join('')}</div><div class="section-heading"><h2>Как устроено занятие</h2></div>`);
 function draw(){
  const sequence=lessonSequence(data.lessons,data.learningPath),course=primary(null,'',true),homes=new Map(sequence.map(record=>[record.lesson.id,record.level]));
  $('#path-main-count',root).textContent=course.length;$('#path-task-count',root).textContent=course.reduce((n,l)=>n+l.exercises.length,0);$('#path-done-count',root).textContent=course.filter(l=>progressLesson(l,data.state).done).length;
  $('#path-main-label',root).textContent=russianPlural(course.length,lessonNouns)+' основной программы';$('#path-task-label',root).textContent=russianPlural(course.reduce((n,l)=>n+l.exercises.length,0),['задание','задания','заданий'])+' со своим ответом';$('#path-done-label',root).textContent=russianPlural(course.filter(l=>progressLesson(l,data.state).done).length,lessonNouns)+' пройдено';
  $$('[data-level]',root).forEach(b=>{const active=b.dataset.level===selected;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
  $$('[data-level-count]',root).forEach(count=>{count.textContent=russianCount(primary(count.dataset.levelCount).length,lessonNouns);});
  if(coverageLevel!==selected){coverageLevel=selected;mountCurriculumCoverage($('#path-coverage',root),data,{level:selected,onLessonsChanged:draw});}
  const meta=data.learningPath?.levels?.find(l=>l.id===selected),all=primary(selected),ls=primary(selected,query,$('#all-levels',root).checked);
  const next=all.find(l=>!progressLesson(l,data.state).done),later=levels.slice(levels.indexOf(selected)+1).find(level=>primary(level).some(l=>!progressLesson(l,data.state).done)),completed=all.filter(l=>progressLesson(l,data.state).done).length;
  const checkpoint=typeof meta?.checkpoint==='string'?meta.checkpoint:meta?.checkpoint?.description||'Проверь себя на новых заданиях: сформулируй ответ без подсказок, получи разбор, исправь текст и объясни свой выбор.';
  $('#level-focus',root).innerHTML=`<div class="level-big">${selected}<small>${selected==='A1'||selected==='A2'?'ПРОВЕРИТЬ ОСНОВЫ':selected==='C1'||selected==='C2'?'УГЛУБИТЬ И УТОЧНИТЬ':'РАЗВИТЬ СВОБОДУ'}</small></div><div><h2>${esc(meta?.title||objectives[selected])}</h2><p>${esc(meta?.goal||objectives[selected])}</p><p>Прогресс этапа: ${completed} из ${all.length}${!next&&all.length?' · Можно перейти дальше или повторить выбранный материал.':'.'}</p><details><summary>Контрольная точка и быстрый проход</summary><p>${esc(checkpoint)}</p><p>Если тема знакома, сначала выполни задания без чтения объяснения. Открывай теорию там, где не уверен. Автоматической отметки «знаю» за просмотр нет.</p></details></div><div class="actions">${next?`<a class="btn primary" href="#/lesson/${esc(next.id)}">${completed||progressLesson(next,data.state).tried?'Продолжить':'Начать'} ${selected} ${icon('arrow')}</a>`:later?`<button class="btn primary" data-path-next-level="${later}">Дальше: ${later} ${icon('arrow')}</button>`:'<a class="btn" href="#/mastery">Проверить навыки '+icon('arrow')+'</a>'}</div>`;
  const nextLevelButton=$('[data-path-next-level]',root);if(nextLevelButton)nextLevelButton.onclick=()=>{selected=later;queueDraft('roadmap-level',selected);draw();};
  const groups=roadmapLessonGroups(ls);
  const renderLesson=l=>{const info=lessonRouteInfo(l.id,data.studyRoute),deepening=info.deepening?{...info.deepening,afterTitle:data.lessons.find(lesson=>lesson.id===info.deepening.afterLessonId)?.title}:null;return roadmapLessonHTML(l,data.state,homes.get(l.id),sourceRelations?sourceRelations(l.id):info.relations,deepening);};
  $('#path-list').innerHTML=ls.length?groups.map(g=>`<section class="path-group"><div class="section-heading"><h2>${esc(g.title)}</h2><span class="small-note">${russianCount(g.lessons.length,lessonNouns)}</span></div><div class="path-list">${g.lessons.map(renderLesson).join('')}</div></section>`).join(''):'<div class="notice">Не нашлось занятий по этому запросу. Попробуй поиск на всех уровнях или открой каталог учебников.</div>';
  const overviews=sequence.filter(record=>lessonRouteInfo(record.lesson.id,data.studyRoute).overview).map(record=>record.lesson);
  $('#path-overviews',root).innerHTML=overviews.length?`<details class="path-consolidation"><summary>Несколько тем вместе · ${russianCount(overviews.length,['обзорное занятие','обзорных занятия','обзорных занятий'])}</summary><p>Необязательное закрепление: собери знакомые конструкции в общей задаче. Эти обзоры доступны отдельно и не увеличивают число новых тем основной программы. Все прежние ответы сохранены.</p><div class="path-list">${overviews.map(renderLesson).join('')}</div></details>`:'';
 }
 $$('[data-level]',root).forEach(b=>b.onclick=()=>{selected=b.dataset.level;queueDraft('roadmap-level',selected);draw();});
 $('#lesson-search').oninput=e=>{query=e.target.value.trim().toLowerCase();draw();};$('#all-levels').onchange=draw;
 $$('[data-path-tab]',root).forEach(b=>b.onclick=()=>{$$('[data-path-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#path-lessons').hidden=b.dataset.pathTab!=='lessons';$('#path-plan').hidden=b.dataset.pathTab!=='plan';});draw();
}
export function mountTenses(root,data){
 const names=[['present-simple','Present Simple','Факт, привычка, состояние','I work / she works','Не временный кадр, а общее положение дел.'],['present-continuous','Present Continuous','Сейчас, временно, в процессе','am / is / are + -ing','Взгляд изнутри ситуации: она происходит или временно актуальна.'],['present-perfect','Present Perfect','До сейчас: результат или опыт','have / has + V3','Важна связь с настоящим; законченное время обычно требует Past Simple.'],['present-perfect-continuous','Present Perfect Continuous','Процесс до сейчас, длительность','have / has been + -ing','В центре деятельность и её продолжительность; не количество результатов.'],['past-simple','Past Simple','Завершённое прошлое','V2 / did + V1','Отдельный эпизод внутри законченного прошлого.'],['past-continuous','Past Continuous','Процесс в момент прошлого','was / were + -ing','Фон, на котором происходит другое событие.'],['past-perfect','Past Perfect','Раньше другой точки в прошлом','had + V3','Порядок двух прошлых событий, когда его нужно уточнить.'],['past-perfect-continuous','Past Perfect Continuous','Длительность до момента прошлого','had been + -ing','Предшествующий процесс объясняет прошлую ситуацию.'],['future-simple','Future Simple','Решение, прогноз, обещание','will + V1','Не универсальный перевод русского будущего; сравни с планом going to.'],['future-continuous','Future Continuous','В процессе в будущем','will be + -ing','Что будет происходить в определённый момент.'],['future-perfect','Future Perfect','Результат к сроку','will have + V3','К этому моменту действие завершится.'],['future-perfect-continuous','Future Perfect Continuous','Длительность к будущему моменту','will have been + -ing','Взгляд назад из будущей точки; форма встречается реже.']];
 const map=data.learningPath?.tenses||[];
 root.innerHTML=heading('Время — это точка зрения.','Выбирай форму по смыслу: когда, процесс или факт, результат или длительность.',`<a class="btn" href="#/roadmap">${icon('map')} Вся программа</a>`)+`<div class="notice">Это учебная карта 12 распространённых сочетаний времени и аспекта. Будущее также выражают going to и формы настоящего; модальность и состояние глагола влияют на выбор. Не каждая английская форма соответствует отдельному русскому времени.</div><div class="tense-grid">${names.map(([id,title,meaning,formula,contrast],i)=>{const entry=map.find(t=>t.id===id||t.title===title),matches=entry?.lessonIds?.map(id=>data.lessons.find(l=>l.id===id)).filter(Boolean)||data.lessons.filter(l=>(l.title+' '+l.subtitle).toLowerCase().includes(title.toLowerCase()));return `<article class="surface tense-card"><div class="spread"><span class="eyebrow">${i<4?'PRESENT':i<8?'PAST':'FUTURE'} / ${String(i%4+1).padStart(2,'0')}</span>${icon('clock')}</div><h2>${title}</h2><strong>${meaning}</strong><code>${formula}</code><p>${contrast}</p><div class="tense-links">${matches.slice(0,3).map(l=>`<a href="#/lesson/${esc(l.id)}">${esc(l.level)} · ${esc(l.title)} ${icon('arrow')}</a>`).join('')||'<a href="#/books">Найти в учебниках →</a>'}</div></article>`;}).join('')}</div><div class="section-heading"><h2>За пределами таблицы</h2></div><div class="grid3">${[['future','Планы и договорённости','Going to, Present Continuous и расписания.'],['modals','Модальность и время','Вероятность, обязанность, совет и предположения о прошлом.'],['passive','Залог и структура','Время сохраняется, меняется фокус: кто действует или что произошло.']].map(([id,t,s])=>`<a class="surface" href="#/lesson/${id}"><h3>${t}</h3><p class="small-note">${s}</p><span class="text-link">Разобраться ${icon('arrow')}</span></a>`).join('')}</div>`;
}
export async function mountLibrary(root,data){
 const route=location.hash;
 const [status,coverage]=await Promise.all([loadBookStatus(data),loadCurriculumCoverage().catch(()=>null)]),supplements=coverage?.bookSupplements;
 data.bookStatus=status;if(!root.isConnected||location.hash!==route)return;
 const all=data.library?.books||[];let filter='',page=0;
 root.innerHTML=heading('Твоя большая библиотека.','Готовые главы твоих учебников: подробные разборы, свои ответы и сохранённый прогресс. Новые книги показаны отдельно по готовности.',`<div class="actions"><a class="btn" href="#/coverage">${icon('spark')} Темы других программ</a><a class="btn" href="#/roadmap">${icon('map')} Программа A1–C2</a></div>`)+`
 <div class="library-overview"><strong>${data.library?.uniqueUnits||0}<span>уникальных юнитов в каталоге</span></strong><p>${all.length} PDF · ${all.filter(b=>!b.duplicateOf).length} разных учебников<br>Grammar · Vocabulary · Collocations · Phrasal verbs</p><span class="pill green">Оглавления текущего каталога сверены</span></div>
 <div class="library-build-summary"><strong>${data.bookStatus?.ready||0} из ${data.bookStatus?.total??data.library?.uniqueUnits??all.filter(b=>!b.duplicateOf).reduce((n,b)=>n+b.units.length,0)}</strong> юнитов разобрано в уроки. Готовые темы отмечены в оглавлении.</div><div class="books-shelf">${all.filter(b=>!b.duplicateOf).map((b,i)=>`<button class="shelf-book" data-book="${b.id}" style="--book-hue:${bookHues[i%bookHues.length]}"><div class="shelf-cover"><span>${/\bin use\b/i.test(b.title)?'IN USE':'COURSEBOOK'}</span><strong>${esc(b.title.replace('English ','').replace(' in Use',''))}</strong><small>${esc(b.level)}</small></div><span>${data.bookStatus?.books?.[b.id]?.ready||0} / ${b.unitCount} уроков готово</span></button>`).join('')}</div>
 <div class="notice small-note">Названия и номера взяты из твоих книг. Одна копия Murphy повторяет те же 145 юнитов. Полный каталог содержит ${data.library?.totalUnits||0} записей; дубль можно включить фильтром. Это юниты книг; отдельно подготовленные занятия приложения находятся в карте A1–C2.</div>
 <div class="section-heading" id="unit-anchor"><h2>Оглавления целиком</h2><span id="unit-count" class="small-note"></span></div><div class="card"><div class="filters"><div class="search">${icon('search')}<input id="unit-search" aria-label="Поиск по всем оглавлениям" placeholder="Тема, выражение или номер юнита…"></div><select id="unit-book" aria-label="Выбор учебника"><option value="">Все учебники</option>${all.map(b=>`<option value="${b.id}">${esc(b.title)}${b.duplicateOf?' · повторное издание':''}</option>`).join('')}</select></div><div class="actions library-controls"><label class="small-note"><input type="checkbox" id="include-duplicate"> Включить повторное издание</label><label class="small-note"><input type="checkbox" id="only-unread"> Только непрочитанные</label></div><div id="unit-list"></div><div class="spread pagination"><button class="btn small" id="units-prev">← Назад</button><span id="units-page" class="small-note"></span><button class="btn small" id="units-next">Далее →</button></div></div>`;
 $('.library-build-summary',root).insertAdjacentHTML('beforebegin','<section id="library-coverage" aria-label="Расширение программы и справочники"></section>');
 $('.library-build-summary',root).insertAdjacentHTML('afterend','<section class="notice small-note" id="library-book-intake" aria-label="Готовность новых учебников"></section>');
 $('#library-book-intake',root).innerHTML=bookIntakeNotice(status,data.library?.uniqueUnits||0);
 mountCurriculumCoverage($('#library-coverage',root),data,{compact:true});
 if(supplements?.books){root.insertAdjacentHTML('beforeend',`<div class="section-heading"><h2>Приложения и справочники</h2><span class="small-note">За пределами основных юнитов</span></div><p class="small-note">Таблицы неправильных глаголов, фонетические символы, грамматические справочники и смешанное повторение. Здесь доступны исходные разделы книг; это не отдельные подготовленные уроки.</p><div class="book-supplements">${supplements.books.filter(b=>b.entries.length).map(b=>`<details class="surface"><summary>${esc(all.find(x=>x.id===b.bookId)?.title||b.bookId)} <span>${b.entries.length}</span></summary><div>${b.entries.map(e=>`<a href="/books/${encodeURIComponent(b.filename)}#page=${e.page}" target="_blank" rel="noopener"><strong>${esc(e.title)}</strong><span>PDF ${e.page}–${e.endPage} ${icon('arrow')}</span></a>`).join('')}</div></details>`).join('')}</div>`);}
 function draw(){
  const q=$('#unit-search',root).value,read=readLibraryUnits(all,data.state.read),books=all.filter(b=>(!filter||b.id===filter)&&(!b.duplicateOf||$('#include-duplicate',root).checked||filter===b.id)),units=books.flatMap(book=>book.units.map(unit=>({book,unit}))).filter(({book,unit})=>(!$('#only-unread',root).checked||!read.has(unit.equivalentUnitId||unit.id))&&libraryUnitMatches(book,unit,q));
  page=Math.max(0,Math.min(page,Math.ceil(units.length/40)-1));$('#unit-count').textContent=units.length+' юнитов';
  $('#unit-list',root).innerHTML=units.slice(page*40,(page+1)*40).map(({book:b,unit:u})=>{const state=libraryUnitStatus(u,data.bookStatus,read,b.level);return `<a class="unit-row" href="#/unit/${esc(u.id)}"><span class="unit-number">${String(u.unit).padStart(3,'0')}</span><div><h3>${esc(u.title)}</h3><p>${esc(b.title)} · ${esc(u.category||'')} · PDF ${u.page}–${u.endPage}</p></div><span class="pill ${state.tone}">${esc(state.label)}</span>${icon('arrow')}</a>`;}).join('')||'<p class="small-note">По этому запросу ничего не нашлось.</p>';
  $('#units-prev').disabled=page===0;$('#units-next').disabled=(page+1)*40>=units.length;$('#units-page').textContent=units.length?`${page*40+1}–${Math.min((page+1)*40,units.length)} из ${units.length}`:'0';
 }
 $('#unit-search').oninput=()=>{page=0;draw();};$('#unit-book').onchange=e=>{filter=e.target.value;page=0;draw();};$('#include-duplicate').onchange=$('#only-unread').onchange=()=>{page=0;draw();};
 $('#units-prev').onclick=()=>{page--;draw();$('#unit-anchor').scrollIntoView();};$('#units-next').onclick=()=>{page++;draw();$('#unit-anchor').scrollIntoView();};
 $$('[data-book]',root).forEach(b=>b.onclick=()=>{filter=b.dataset.book;$('#unit-book').value=filter;syncSelect($('#unit-book'));page=0;draw();$('#unit-anchor').scrollIntoView({behavior:'smooth'});});draw();
 async function updateBookAvailability(){if(!root.isConnected||location.hash!==route)return;try{const response=await fetch('/book-content/status.json');if(response.ok){const status=await response.json();if(!root.isConnected||location.hash!==route)return;data.bookStatus=status;$('#library-book-intake',root).innerHTML=bookIntakeNotice(status,data.library?.uniqueUnits||0);const summary=$('.library-build-summary',root);summary.innerHTML=`<strong>${status.ready||0} из ${data.bookStatus?.total??data.library?.uniqueUnits??all.filter(b=>!b.duplicateOf).reduce((n,b)=>n+b.units.length,0)}</strong> юнитов разобрано в уроки. ${status.state==='paused'?'Обработка приостановлена; готовые уроки доступны.':'Готовые темы отмечены в оглавлении.'}`;$$('[data-book]',root).forEach(b=>{const count=b.querySelector(':scope > span');if(count)count.textContent=(status.books?.[b.dataset.book]?.ready||0)+' / '+(all.find(x=>x.id===b.dataset.book)?.unitCount||0)+' уроков готово';});draw();}}catch{}if(root.isConnected&&location.hash===route)setTimeout(updateBookAvailability,30000);}
 setTimeout(updateBookAvailability,30000);
}
export {mountBookUnit as mountUnit} from './book-reader.js';
