import {$,$$,api,esc,icon,empty} from './core.js';
import {masterySummary,masteryDomains,masteryStatuses,evidenceTarget} from './mastery-model.js';
const coverage={practice:'Подготовлена практика',partial:'Есть ограничения',gap:'Нужно дополнить'};
const mounts=new WeakMap();
export async function mountMastery(root,data,refresh,requested=''){
 const token={};mounts.set(root,token);let route=location.hash;
 const current=()=>mounts.get(root)===token&&root.isConnected&&location.hash===route;
 root.innerHTML='<p class="small-note">Открываем карту результатов…</p>';
 const [catalog,projects]=await Promise.all([api('/curriculum/mastery'),api('/projects')]);if(!current())return;
 data={...data,masteryBookVersions:catalog.currentBookExercises,masteryProjects:projects};
 let selected=catalog.levels.find(l=>l.level===requested)?.level||'B1',domain='',filter='all';
 function draw(){
  if(!current())return;
  const level=catalog.levels.find(l=>l.level===selected),summary=masterySummary(level,data);
  const rows=summary.indicators.filter(i=>(!domain||i.domain===domain)&&(filter==='all'||filter==='new'&&!i.progress.answers||filter==='partial'&&i.coverage!=='practice'||filter==='reviewed'&&['reviewed','retained'].includes(i.progress.status)));
  root.innerHTML=`<div class="mastery-page"><header class="mastery-header"><div><span class="eyebrow">ПРОГРАММА И ТВОИ РЕЗУЛЬТАТЫ</span><h1>От «я знаю правило»<br>к «я могу это сделать»</h1><p>У каждого уровня есть конкретные речевые задачи, подготовленная практика и критерии. Ответы, исправления и применение в другой ситуации показывают, что стоит тренировать дальше.</p></div><a class="btn" href="#/projects">${icon('pen')} Проекты и проверки</a></header>
  <nav class="mastery-levels" aria-label="Уровень программы">${catalog.levels.map(l=>`<button data-mastery-level="${esc(l.level)}" aria-pressed="${l.level===selected}">${esc(l.level)}<small>${masterySummary(l,data).practiced} / ${l.indicators.length} с практикой</small></button>`).join('')}</nav>
  <div class="mastery-facts"><article><strong>${summary.total}</strong><span>результатов обучения<br>в этом уровне</span></article><article><strong>${summary.practiced}</strong><span>с твоими<br>ответами</span></article><article><strong>${summary.reviewed}</strong><span>проверены<br>в упражнениях</span></article><article><strong>${summary.retained}</strong><span>применены в новой ситуации<br>через 7 дней или позже</span></article></div>
  <div class="mastery-tools"><label>Область<select id="mastery-domain"><option value="">Все стороны языка</option>${Object.entries(masteryDomains).map(([id,title])=>`<option value="${id}" ${domain===id?'selected':''}>${title}</option>`).join('')}</select></label><label>Показать<select id="mastery-filter">${[['all','Все результаты'],['new','Ещё без моих ответов'],['partial','Ограничения программы'],['reviewed','Проверено в упражнениях']].map(([id,title])=>`<option value="${id}" ${filter===id?'selected':''}>${title}</option>`).join('')}</select></label><a href="#/books">Все темы учебников ${icon('arrow')}</a></div>
  <section class="mastery-grid" aria-label="Результаты обучения">${rows.length?rows.map(i=>`<article class="mastery-card"><div class="mastery-card-top"><span>${esc(masteryDomains[i.domain]||i.domain)}</span><span class="mastery-coverage ${esc(i.coverage)}">${coverage[i.coverage]||'Проверяется'}</span></div><h2>${esc(i.title)}</h2><p>${esc(i.canDo)}</p><div class="mastery-evidence"><strong>${masteryStatuses[i.progress.status]}</strong><span>Ответов: ${i.progress.answers} · Принято: ${i.progress.accepted}</span></div><details><summary>Как убедиться, что получается</summary><p>${esc(i.demonstration?.task||'')}</p><ul>${(i.demonstration?.criteria||[]).map(c=>`<li>${esc(c)}</li>`).join('')}</ul><p class="small-note">Для отметки проверки: минимум ${i.progress.minimum} разных принятых заданий. Для закрепления — новый ответ в разделе «Закрепление» или перенос проекта спустя минимум 7 дней. Простое перечитывание здесь не учитывается.</p>${i.demonstration?.requiresAudio?'<p class="small-note">Нужна устная практика. Расшифровка сама по себе не оценивает произношение.</p>':''}</details><div class="mastery-links">${(i.evidence||[]).map(e=>{const t=evidenceTarget(e);return `<a href="${esc(t.href)}">${esc(e.note||e.lessonId||e.unitId)} ${icon('arrow')}</a>`;}).join('')}</div>${i.limitations?.length?`<details class="mastery-limitations"><summary>Что ещё потребуется</summary><ul>${i.limitations.map(l=>`<li>${esc(l)}</li>`).join('')}</ul></details>`:''}</article>`).join(''):empty('Нет результатов по этому фильтру','Выбери другую область или покажи все результаты.')}</section>
  <details class="mastery-method"><summary>Как читать эту карту и откуда взята программа</summary><p>${esc(catalog.scope||'')}</p><p>Это карта учебной программы, а не присвоение CEFR. Отметка «проверено» относится к ответам в приложении. Для свободного диалога, естественного аудирования, произношения и экзаменационного уровня нужны отдельные работы и обратная связь. Участки с ограничениями показаны явно.</p><p>Список всех тем из оглавлений находится в учебниках. Здесь собраны проверяемые результаты, которые объединяют несколько тем.</p><ul>${(catalog.sources||[]).map(s=>`<li>${/^https:\/\//.test(s.url||'')?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.id)}</a>`:esc(s.title||s.id)}</li>`).join('')}</ul></details></div>`;
  $$('[data-mastery-level]',root).forEach(b=>b.onclick=()=>{if(!current())return;selected=b.dataset.masteryLevel;history.replaceState(null,'','#/mastery/'+selected);route=location.hash;draw();});
  $('#mastery-domain',root).onchange=e=>{domain=e.target.value;draw();};$('#mastery-filter',root).onchange=e=>{filter=e.target.value;draw();};
 }
 draw();
}
