package bot

// Prompt is one letter assignment: an English task line and a short Russian hint.
type Prompt struct {
	EN string
	RU string
}

// Prompts is the rotation pool of letter assignments.
var Prompts = []Prompt{
	{"Leave a code review on a pull request that adds a third caching layer nobody asked for.", "Скажи «нет» вежливо, но так, чтобы автор не пошёл переделывать всё заново."},
	{"Write the incident postmortem for a 40-minute outage caused by a missing index on a hot table.", "Факты, таймлайн, что чинишь. Без «мы глубоко сожалеем»."},
	{"Message your teammate Jake: you're taking over his ticket because he's out sick, ask what's half-done.", "Обычный рабочий пинг в Slack, коротко и по-человечески."},
	{"Write a blog post intro about why you moved a service from Postgres LISTEN/NOTIFY to a real queue.", "Первые 2-3 абзаца поста. Тон — сухой, без «давайте разберёмся!»."},
	{"Complain to your ISP: the connection drops every evening between 7 and 11 and support keeps closing tickets.", "Жалоба. Конкретика, требование, дедлайн."},
	{"Plan a two-week vacation with a friend: dates, budget, who books what.", "Письмо другу. Живой разговорный тон."},
	{"Explain your service's architecture to a new hire in one message: what talks to what and why.", "Объясняй как коллеге, не как в документации."},
	{"Turn down a recruiter politely but leave the door open for later.", "Отказ. Не мост сжигать, но и не тянуть переписку."},
	{"Ask your manager for a raise: what you shipped this year and what number you want.", "Прямо, с цифрами, без извинений."},
	{"Write a bug report for a race condition you can only reproduce one time in twenty.", "Шаги, ожидаемое, фактическое, почему воспроизводится редко."},
	{"Reply to a customer whose data export has been stuck for two days. You still don't know why.", "Честно про статус, не обещай то, чего не знаешь."},
	{"Push back on a deadline: the feature needs three weeks, you were given one.", "Предложи, что можно урезать, а не просто «не успеем»."},
	{"Write release notes for a version that breaks an API two clients depend on.", "Что сломалось, как мигрировать, к какой дате."},
	{"Ask a stranger on GitHub to look at your PR that's been sitting unreviewed for two weeks.", "Вежливый пинг в опенсорсе, без нытья."},
	{"Describe your morning routine on a day when everything went wrong.", "Личное, с деталями и сухим юмором."},
	{"Write a Slack message announcing you're on call this week and how to reach you.", "Короткое объявление в канал."},
	{"Argue for using a boring technology instead of the shiny one your teammate wants.", "Аргументы, а не снобизм."},
	{"Email your landlord: the heating has been broken for five days and you want it fixed or rent reduced.", "Твёрдо, вежливо, с датами."},
	{"Write a message to a friend who cancelled plans on you twice in a row.", "Без драмы, но чтобы он понял."},
	{"Document a tricky function so the version of you in six months doesn't hate you.", "Комментарий/док в прозе, объясняй зачем, а не что."},
	{"Write your part of a standup update after a day where you mostly read code and fixed nothing.", "Честно, без раздувания."},
	{"Ask for help in a public channel about a Go memory leak you can't pin down.", "Что пробовал, что видишь, что нужно."},
	{"Write a review for a restaurant that was great except for one thing that ruined it.", "Живой отзыв, конкретика, без звёздочек-клише."},
	{"Explain to a non-technical friend what your job actually is, day to day.", "Без жаргона, но и не как для ребёнка."},
	{"Write a message rejecting a candidate after a technical interview that went badly.", "Уважительно, конкретно, коротко."},
	{"Convince your team to delete a feature nobody uses but everyone is afraid to touch.", "Данные + план удаления."},
	{"Write a note to yourself explaining a decision you're about to make, for the future postmortem.", "Поток мысли, но структурный."},
	{"Reply to a passive-aggressive comment on your pull request.", "Не отвечать в тон, но и не прогибаться."},
	{"Ask your team to stop scheduling meetings after 6 pm.", "Границы, вежливо и без пассивной агрессии."},
	{"Write a short proposal for spending two weeks paying down tech debt in the billing service.", "Что болит, что чинишь, что получится."},
	{"Describe the worst on-call night you've had.", "История, живая, с деталями времени и сумм."},
	{"Write a message to a friend who just got laid off.", "Без банальностей и без «всё к лучшему»."},
	{"Explain why the estimate you gave was wrong by a factor of three.", "Разбор без самобичевания."},
	{"Write a comment on a Hacker News thread arguing that microservices were a mistake for your team.", "С опытом, без манифеста."},
	{"Ask your bank why a payment was declined three times and what you should do.", "Официальный, но живой тон."},
	{"Write a welcome message for a new teammate joining your Go backend team on Monday.", "Тепло, конкретно, что делать в первый день."},
	{"Describe a piece of code you're proud of and why.", "Гордость без хвастовства."},
	{"Write a message cancelling a subscription and asking for a partial refund.", "Твёрдо и по делу."},
	{"Explain to your manager why you want to switch from the platform team to the product team.", "Мотивы, а не жалобы."},
	{"Write a short guide: how to run the project locally without losing your mind.", "Инструкция человеческим языком."},
	{"Tell a friend about a book that changed how you think about your work.", "Личное письмо, не рецензия."},
	{"Write a message to a contractor whose invoice is 30% higher than the quote.", "Спокойно, с фактами, с вопросом."},
	{"Explain the difference between two approaches you considered and why you picked one.", "Взвешенно, оба варианта всерьёз."},
	{"Write a message to your neighbor Danny about the noise on weeknights.", "Соседский тон: не воевать, но решить."},
	{"Draft a reply to a user who wrote an angry review of your app.", "Не оправдываться, но и не отмахнуться."},
	{"Write a message asking a colleague to pair with you on a nasty debugging session.", "Просьба, без «если тебе не сложно» пять раз."},
	{"Describe what you'd change about your team's process if you had a free hand.", "Мнение, конкретика, приоритеты."},
	{"Write a message negotiating a start date after accepting a job offer.", "Аккуратно, но с твоей позицией."},
	{"Explain to a junior why their code works but is still a problem.", "Учить, а не унижать."},
	{"Write a message to a friend inviting them to a weekend trip you already half-planned.", "Разговорный, живой, с деталями."},
	{"Report to your team that a third-party API you depend on is deprecating an endpoint in 60 days.", "Что это значит для нас и кто что делает."},
	{"Write a short letter to your past self, one year into this job.", "Личное, без пафоса."},
	{"Ask for feedback on your work from someone who owes you nothing.", "Конкретный запрос, а не «что думаешь?»."},
	{"Write a message explaining that you'll be offline for two days and who covers what.", "Короткое, полное, ничего не забыть."},
	{"Describe a technical decision your team made that you still disagree with.", "Без обиды, с аргументами."},
	{"Write a message to support of a service that lost your data, asking what exactly happened.", "Жёстко, но по делу, требуй деталей."},
	{"Explain why you'd rather write a script than do a task manually one more time.", "Полушутя, но с аргументом."},
	{"Write a message to a friend describing the city you live in, honestly.", "Живо, с конкретными местами, без туристического глянца."},
	{"Draft a short talk proposal for a Go meetup based on something you shipped.", "Заявка: проблема, что расскажешь, кому полезно."},
	{"Write a message to your team after you shipped something that broke, and you fixed it.", "Ответственность без драмы."},
}
