import test from 'node:test';
import assert from 'node:assert/strict';
import {studyUI,deferred} from './study-ui-fixture.mjs';
const scenario={id:'repair',level:'B1',title:'Laptop repair',goal:'Explain and negotiate a repair.',opening:'How can I help?'};
const catalog={scenarios:[scenario],maxTurns:6},sid='session-review-test';
const feedback=b=>({...b,at:new Date().toISOString(),feedback:{source:'reference',verdict:'ungraded',summary:'Saved comparison',explanation:'Review your meaning.',mistakes:[]}});
function stored(turns=[]){return {version:1,id:sid,scenarioId:'repair',turns};}
function turn(id='turn-one'){return {id,answer:'My laptop needs a new battery.',reply:'Can you bring it tomorrow?',mode:'writing',at:new Date().toISOString()};}
async function fixture(t,session=stored()){
 const f=await studyUI(t,'conversation.js');window.addEventListener=()=>{};window.removeEventListener=()=>{};window.dispatchEvent=()=>{};location.hash='#/conversation/repair/'+sid;
 f.data={settings:{provider:'offline'},state:{attempts:[],drafts:{['conversation:v1:'+sid]:{text:JSON.stringify(session)}}}};f.session=session;f.queueDraft=async(key,text)=>{f.data.state.drafts[key]={text};};f.refresh=async()=>f.data;
 f.api=async(path,b)=>{if(path==='/conversation/scenarios')return catalog;if(path==='/conversation/turn'){f.session={...f.session,turns:[...f.session.turns,{id:b.requestID,answer:b.answer,reply:'I can help. What time works?',mode:b.mode,at:new Date().toISOString()}]};f.data.state.drafts['conversation:v1:'+sid]={text:JSON.stringify(f.session)};return f.session;}if(path==='/check'){const result=feedback(b);f.data.state.attempts.push(result);return result;}throw Error(path);};return f;
}
const mount=f=>f.module.mountConversation(f.root,f.data,f.refresh,'repair',sid);
test('spoken draft provenance survives reload and manual editing becomes writing',async t=>{const f=await fixture(t);await mount(f);f.voice=async(_button,input,_settings,onText)=>{input.value='I need the laptop for my work tomorrow.';onText();};await f.root.querySelector('#conversation-voice').click();await mount(f);await f.root.querySelector('#conversation-send').click();assert.equal(f.requests.find(r=>r.path==='/conversation/turn').body.mode,'speaking');const input=f.root.querySelector('#conversation-answer');input.value='A typed follow-up about the price.';input.oninput();await f.root.querySelector('#conversation-send').click();assert.equal(f.requests.filter(r=>r.path==='/conversation/turn').at(-1).body.mode,'writing');});
test('an old mount cannot redraw the same route after a late reply',async t=>{const f=await fixture(t);await mount(f);const input=f.root.querySelector('#conversation-answer');input.value='Please tell me the repair price.';input.oninput();const pending=deferred(),normal=f.api;f.api=(path,b)=>path==='/conversation/turn'?pending.promise:normal(path,b);const sending=f.root.querySelector('#conversation-send').click();await new Promise(r=>setImmediate(r));const payload=f.requests.at(-1).body;await mount(f);const current=f.root.querySelector('#conversation-answer');current.value='This is a newer draft on the reopened route.';current.oninput();pending.resolve(stored([{id:payload.requestID,answer:payload.answer,reply:'It costs ninety-five dollars.',mode:'writing',at:new Date().toISOString()}]));await sending;assert.equal(f.root.querySelector('#conversation-answer'),current);assert.equal(current.value,'This is a newer draft on the reopened route.');});
test('review result for an earlier turn never appears under a newer conversation version',async t=>{const f=await fixture(t,stored([turn()]));await mount(f);const pending=deferred(),normal=f.api;f.api=(path,b)=>path==='/check'?pending.promise:normal(path,b);const reviewing=f.root.querySelector('#conversation-review').click();await new Promise(r=>setImmediate(r));const payload=f.requests.find(r=>r.path==='/check').body;const input=f.root.querySelector('#conversation-answer');input.value='Yes, I can bring it tomorrow morning.';input.oninput();await f.root.querySelector('#conversation-send').click();assert.equal(f.root.querySelector('#conversation-feedback').innerHTML,'');pending.resolve(feedback(payload));await reviewing;assert.equal(f.root.querySelector('#conversation-feedback').innerHTML,'');assert.equal(payload.lessonId,'conversation');assert.equal(payload.exerciseId,sid+'-1');assert.equal(payload.context,undefined);});
test('successful server reply remains visible when refreshing bootstrap fails',async t=>{const f=await fixture(t);await mount(f);const input=f.root.querySelector('#conversation-answer');input.value='Could you check my battery, please?';input.oninput();f.refresh=async()=>{throw Error('temporary connection failure');};await f.module.mountConversation(f.root,f.data,f.refresh,'repair',sid);await f.root.querySelector('#conversation-send').click();assert.match(f.root.innerHTML,/Could you check my battery/);assert.equal(f.root.querySelector('#conversation-answer').value,'');assert.ok(f.alerts.some(x=>x.includes('Реплика сохранена')));});
test('retrying a review reuses its request id, including after remount',async t=>{const f=await fixture(t,stored([turn()]));await mount(f);await f.root.querySelector('#conversation-review').click();const first=f.requests.find(r=>r.path==='/check').body.id;await f.root.querySelector('#conversation-review').click();await mount(f);await f.root.querySelector('#conversation-review').click();assert.deepEqual(f.requests.filter(r=>r.path==='/check').map(r=>r.body.id),[first,first,first]);});
test('offline partner failure preserves own text and creates no assessed evidence',async t=>{const f=await fixture(t);await mount(f);const input=f.root.querySelector('#conversation-answer');input.value='I need a repair before Friday.';input.oninput();f.api=async()=>{throw Error('Подключите помощника');};await f.root.querySelector('#conversation-send').click();assert.equal(input.value,'I need a repair before Friday.');assert.equal(input.disabled,false);assert.equal(f.local.get('conversation:answer:'+sid+':0'),input.value);assert.equal(f.data.state.attempts.length,0);assert.equal(f.session.turns.length,0);});
test('a newer saved conversation from refresh is not replaced by an older reply snapshot',async t=>{const f=await fixture(t);f.refresh=async()=>{const fresh={...f.session,turns:[...f.session.turns,{...turn('other-tab-turn'),answer:'A newer reply from another view.'}]};return {...f.data,state:{...f.data.state,drafts:{...f.data.state.drafts,['conversation:v1:'+sid]:{text:JSON.stringify(fresh)}}}};};await mount(f);const input=f.root.querySelector('#conversation-answer');input.value='What is the cost of the repair?';input.oninput();await f.root.querySelector('#conversation-send').click();assert.match(f.root.innerHTML,/A newer reply from another view/);assert.match(f.root.innerHTML,/2 \/ 6/);});
