import test from 'node:test';
import assert from 'node:assert/strict';
import {indicatorProgress,evidenceTarget} from '../mastery-model.js';
const start='2026-01-01T12:00:00Z',now='2026-01-10T12:00:00Z';
const indicator={domain:'writing',evidence:[{lessonId:'lesson-one',exerciseIds:['e1','e2']}],demonstration:{minAttempts:2,delayedDays:7}};
const answer=(id,exerciseId,overrides={})=>({id,lessonId:'lesson-one',exerciseId,answer:'My original complete message '+id,at:start,mode:'writing',feedback:{verdict:'correct',source:'codex'},...overrides});
test('read marks and time never create skill evidence',()=>{assert.equal(indicatorProgress(indicator,{state:{read:{'lesson-one':start},activity:{day:7200}}},now).status,'new');});
test('two different graded exercises are needed; retries are not two skills',()=>{const state={attempts:[answer('a','e1'),answer('b','e1')]};assert.equal(indicatorProgress(indicator,{state},now).status,'practiced');state.attempts.push(answer('c','e2'));assert.equal(indicatorProgress(indicator,{state},now).status,'reviewed');});
test('offline and ungraded responses are practice, never passing work',()=>{assert.equal(indicatorProgress(indicator,{state:{attempts:[answer('a','e1',{feedback:{verdict:'correct',source:'reference'}}),answer('b','e2',{feedback:{verdict:'ungraded',source:'codex'}})]}},now).status,'practiced');});
test('a later unsuccessful answer supersedes an earlier success',()=>{const attempts=[answer('a','e1'),answer('b','e2'),answer('c','e1',{at:'2026-01-02T12:00:00Z',feedback:{verdict:'partial',source:'codex'}})];assert.equal(indicatorProgress(indicator,{state:{attempts}},now).status,'practiced');});
test('transfer requires a different situation after a real delay; copied text does not qualify',()=>{const attempts=[answer('a','e1'),answer('b','e2')];const transfer=answer('c','transfer-v1-lesson-one-r1-write',{lessonId:'free',at:'2026-01-09T12:00:00Z'});assert.equal(indicatorProgress(indicator,{state:{attempts:[...attempts,transfer]}},now).status,'retained');assert.equal(indicatorProgress(indicator,{state:{attempts:[...attempts,{...transfer,at:'2026-01-02T12:00:00Z'}]}},now).status,'reviewed');assert.equal(indicatorProgress(indicator,{state:{attempts:[...attempts,{...transfer,answer:attempts[0].answer}]}},now).status,'reviewed');});
test('future attempts and transfer to another topic do not qualify',()=>{const attempts=[answer('a','e1'),answer('b','e2')];assert.equal(indicatorProgress(indicator,{state:{attempts}},'2025-01-01').status,'new');attempts.push(answer('c','transfer-v1-other-r1-write',{lessonId:'free',at:now}));assert.equal(indicatorProgress(indicator,{state:{attempts}},now).status,'reviewed');});
test('phonology and live interaction retain external assessment boundary',()=>{const data={state:{attempts:[answer('a','e1'),answer('b','e2')]}};assert.equal(indicatorProgress({...indicator,domain:'phonology'},data,now).status,'external');assert.equal(indicatorProgress({...indicator,demonstration:{requiresPartner:true}},data,now).status,'external');assert.equal(indicatorProgress({...indicator,demonstration:{requiresAudio:true}},data,now).status,'practiced');});
test('published version prevents old book answer reuse',()=>{const i={...indicator,evidence:[{unitId:'grammar-001',exerciseIds:['e1','e2']}]},data={bookStatus:{units:{'grammar-001':{exerciseIds:['e1--aaaaaaaaaaaaaaaa','e2--bbbbbbbbbbbbbbbb']}}},state:{attempts:[answer('a','e1--1111111111111111',{lessonId:'book-grammar-001'}),answer('b','e2--bbbbbbbbbbbbbbbb',{lessonId:'book-grammar-001'})]}};assert.equal(indicatorProgress(i,data,now).accepted,1);});
test('project targets navigate to actual prepared project routes',()=>{assert.equal(evidenceTarget({lessonId:'project-c2-project-archive'}).href,'#/projects/c2-project-archive');});

test('invalid calendar dates cannot become skill evidence through Date.parse normalization',()=>{
 const attempts=[answer('a','e1',{at:'2026-02-31T12:00:00Z'}),answer('b','e2',{at:'2026-02-28T12:00:00Z'})];
 assert.equal(indicatorProgress(indicator,{state:{attempts}},'2026-03-10T12:00:00Z').accepted,1);
});
test('unknown imported source cannot masquerade as a graded answer',()=>{const attempts=[answer('a','e1',{feedback:{verdict:'correct',source:'forged'}}),answer('b','e2')];assert.equal(indicatorProgress(indicator,{state:{attempts}},now).status,'practiced');});
test('the retention interval begins after the necessary prerequisites, not before them',()=>{const attempts=[answer('a','e1'),answer('b','e2',{at:'2026-01-10T12:00:00Z'}),answer('t','transfer-v1-lesson-one-r1-write',{lessonId:'free',at:'2026-01-08T12:00:00Z'})];assert.equal(indicatorProgress(indicator,{state:{attempts}},'2026-01-20').status,'reviewed');});
test('newer unsuccessful transfer supersedes its previous accepted version',()=>{const attempts=[answer('a','e1'),answer('b','e2'),answer('t','transfer-v1-lesson-one-r1-write',{lessonId:'free',at:'2026-01-09T12:00:00Z'}),answer('u','transfer-v1-lesson-one-r1-write',{lessonId:'free',at:'2026-01-10T12:00:00Z',feedback:{verdict:'partial',source:'codex'}})];assert.equal(indicatorProgress(indicator,{state:{attempts}},now).status,'reviewed');});
test('an isolated project transfer does not bypass project recording and revision evidence',()=>{const i={...indicator,evidence:[{lessonId:'project-example',exerciseIds:['e1','e2']}]},attempts=[answer('a','e1',{lessonId:'project-example'}),answer('b','e2',{lessonId:'project-example'}),answer('t','transfer',{lessonId:'project-example',at:now})];assert.equal(indicatorProgress(i,{state:{attempts}},now).status,'reviewed');});
test('pronunciation notes link to the pronunciation route and retain their real stored identity',()=>{const i={domain:'phonology',evidence:[{lessonId:'pron-15-rhythm-and-linking',exerciseIds:[]}]};assert.equal(evidenceTarget(i.evidence[0]).href,'#/pronunciation/pron-15-rhythm-and-linking');assert.equal(indicatorProgress(i,{state:{attempts:[answer('p','pron-15-rhythm-and-linking',{lessonId:'pronunciation'})]}},now).status,'external');});
