import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {studyUI,deferred} from './study-ui-fixture.mjs';
import {projectKey,projectReceiptKey} from '../projects-model.js';
const catalog=JSON.parse(await readFile(new URL('../../content/projects-checkpoints.json',import.meta.url),'utf8')),unit=catalog.units[0];
const result=b=>({...b,at:new Date().toISOString(),feedback:{source:'reference',verdict:'ungraded',summary:'Сохранено для сравнения',explanation:'Сопоставь ответ с источником.',mistakes:[],alternatives:[]}});
async function fixture(t){const f=await studyUI(t,'projects.js');window.addEventListener=()=>{};window.removeEventListener=()=>{};window.dispatchEvent=()=>{};location.hash='#/projects/'+unit.id;f.data={settings:{},state:{drafts:{},attempts:[],read:{}}};f.refresh=async()=>f.data;f.queueDraft=async(key,text)=>{f.data.state.drafts[key]={text};};f.api=async(path,body)=>{if(path==='/projects')return catalog;if(path==='/check'){const a=result(body);f.data.state.attempts.push(a);return a;}throw Error('Unexpected '+path);};return f;}
const stage=(f,id)=>f.root.querySelectorAll('[data-project-stage]').find(e=>e.dataset.projectStage===id).click();
test('models are absent before a saved attempt; revision and delayed transfer are locked',async t=>{const f=await fixture(t);await f.module.mountProjects(f.root,f.data,f.refresh,unit.id);assert.equal(f.root.querySelector('#project-model'),null);stage(f,'revision');assert.equal(f.root.querySelector('#project-answer'),null);stage(f,'transfer');assert.equal(f.root.querySelector('#project-answer'),null);stage(f,'reading');const a=f.root.querySelector('#project-answer');a.value='The door is blue and I should bring a drink.';a.oninput();await f.root.querySelector('#project-check').click();assert.ok(f.root.querySelector('#project-model'));assert.equal(f.data.state.attempts[0].lessonId,'project-'+unit.id);assert.equal(f.data.state.attempts[0].exerciseId,'reading');});
test('a saved answer immediately updates status and stage and adds a collapsed model without replacing the editor',async t=>{const f=await fixture(t);await f.module.mountProjects(f.root,f.data,f.refresh,unit.id);const editor=f.root.querySelector('#project-answer'),reading=f.root.querySelectorAll('[data-project-stage]').find(e=>e.dataset.projectStage==='reading');editor.value='  The door is blue and the apartment is on the second floor.  ';editor.oninput();editor.selectionStart=5;editor.selectionEnd=16;editor.selectionDirection='backward';editor.scrollTop=24;const unchanged=editor.value;await f.root.querySelector('#project-check').click();assert.equal(f.root.querySelector('#project-answer'),editor);assert.equal(editor.value,unchanged);assert.deepEqual([editor.selectionStart,editor.selectionEnd,editor.selectionDirection,editor.scrollTop],[5,16,'backward',24]);assert.match(f.root.querySelector('#project-status').textContent,/Сохранено 1 из 5/);assert.match(f.root.querySelector('#project-status').textContent,/без оценки/);assert.equal(reading.attrs['data-project-done'],'true');assert.match(reading.innerHTML,/<svg/);assert.equal(reading.classList.contains('primary'),true);const model=f.root.querySelector('#project-model');assert.ok(model);assert.equal(Boolean(model.open),false);const first=f.requests.find(r=>r.path==='/check').body;assert.equal(JSON.parse(f.local.get(projectReceiptKey('conditions',unit.id,first.id))).model,false);model.open=true;model.ontoggle();editor.value='I improved my answer after comparing it with the model.';editor.oninput();await f.root.querySelector('#project-check').click();const second=f.requests.filter(r=>r.path==='/check').at(-1).body;assert.equal(JSON.parse(f.local.get(projectReceiptKey('conditions',unit.id,second.id))).model,true);assert.equal(f.root.querySelector('#project-model'),model);});
test('confirmed result updates the current stage even when refresh returns an older snapshot',async t=>{const f=await fixture(t);await f.module.mountProjects(f.root,f.data,f.refresh,unit.id);const editor=f.root.querySelector('#project-answer');editor.value='The blue door leads to the second-floor apartment.';editor.oninput();f.api=async(path,body)=>{assert.equal(path,'/check');return result(body);};await f.root.querySelector('#project-check').click();assert.match(f.root.querySelector('#project-status').textContent,/Сохранено 1 из 5/);assert.ok(f.root.querySelector('#project-model'));assert.equal(f.root.querySelector('#project-answer'),editor);});
test('a late assessment preserves newer text and route navigation',async t=>{const f=await fixture(t);await f.module.mountProjects(f.root,f.data,f.refresh,unit.id);const a=f.root.querySelector('#project-answer');a.value='My first substantive answer to the reading task.';a.oninput();const pending=deferred();f.api=(path)=>{assert.equal(path,'/check');return pending.promise;};const checking=f.root.querySelector('#project-check').click();await new Promise(r=>setImmediate(r));const payload=f.requests.at(-1).body;a.value='My newer draft must remain visible after the request.';a.oninput();pending.resolve(result(payload));await checking;assert.equal(a.value,'My newer draft must remain visible after the request.');assert.equal(f.local.get(projectKey(unit.id,'reading')),a.value);assert.equal(f.root.querySelector('#project-feedback').innerHTML,'');assert.ok(f.alerts.some(x=>x.includes('предыдущей версии')));});
test('typed rehearsal cannot submit as speaking; a stored recording is bound to the submitted transcript',async t=>{const f=await fixture(t);await f.module.mountProjects(f.root,f.data,f.refresh,unit.id);stage(f,'speaking');const a=f.root.querySelector('#project-answer');a.value='Hello Leo, your room is next to the kitchen.';a.oninput();await f.root.querySelector('#project-check').click();assert.equal(f.requests.filter(r=>r.path==='/check').length,0);const file='a'.repeat(64)+'.webm';f.data.state.drafts[projectKey(unit.id,'audio-speaking')]={text:JSON.stringify({file,at:'2026-01-01T00:00:00Z'})};await f.module.mountProjects(f.root,f.data,f.refresh,unit.id);stage(f,'speaking');await f.root.querySelector('#project-check').click();const submitted=f.requests.find(r=>r.path==='/check').body;assert.equal(submitted.mode,'speaking');const receipt=JSON.parse(f.local.get(projectReceiptKey('recording',unit.id,submitted.id)));assert.equal(receipt.answer,submitted.answer);assert.equal(receipt.file,file);});
test('a recording upload that finishes after leaving is archived without replacing the next editor',async t=>{const f=await fixture(t);await f.module.mountProjects(f.root,f.data,f.refresh,unit.id);stage(f,'speaking');let ready;f.recordOnly=async(_button,_preview,callback)=>{ready=callback;};await f.root.querySelector('#project-record').click();const pending=deferred();f.api=(path)=>{assert.equal(path,'/notebook/audio');return pending.promise;};const saving=ready('blob:recording','audio/webm',new Blob(['original recording']));location.hash='#/today';f.root.innerHTML='<h1 id="next-page">Today</h1>';pending.resolve({audio:'b'.repeat(64)+'.webm'});await saving;assert.ok(f.root.querySelector('#next-page'));assert.ok([...f.local.keys()].some(k=>k.startsWith('project:take:'+unit.id+':')));assert.equal(f.local.has(projectKey(unit.id,'audio-speaking')),false);});
