import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {projectProgress,projectReceiptKey,projectAudioURL} from '../projects-model.js';
const catalog=JSON.parse(await readFile(new URL('../../content/projects-checkpoints.json',import.meta.url),'utf8'));
const unit=catalog.units[0],file='a'.repeat(64)+'.webm';
function fixture(source='codex',verdict='correct'){
 const state={attempts:unit.tasks.map(t=>({id:'try-'+t.id,lessonId:'project-'+unit.id,exerciseId:t.id,answer:'This is my complete original response.',mode:t.kind==='speaking'?'speaking':'writing',at:'2026-01-01T10:00:00Z',feedback:{source,verdict}})),drafts:{},read:{['project-'+unit.id]:'2026-01-01'}};
 const speech=state.attempts.find(a=>a.exerciseId==='speaking');state.drafts[projectReceiptKey('recording',unit.id,speech.id)]={text:JSON.stringify({file,answer:speech.answer})};
 return state;
}
function revise(state){const answer='I revised the invitation and clarified the arrival time.',id='revision-1';state.drafts[projectReceiptKey('revision',unit.id,id)]={text:JSON.stringify({answer,attemptIds:state.attempts.map(a=>a.id)})};state.attempts.push({id,lessonId:'project-'+unit.id,exerciseId:'revision',answer,mode:'writing',at:'2026-01-02T10:00:00Z',feedback:{source:'codex',verdict:'correct'}});}
function transfer(state,at='2026-01-09T10:00:00Z'){state.attempts.push({id:'transfer-1',lessonId:'project-'+unit.id,exerciseId:'transfer',answer:'Here is an original response for the new situation.',at,feedback:{source:'codex',verdict:'correct'}});}
test('read flags and arbitrary drafts cannot complete an artifact',()=>{const p=projectProgress(unit,{read:{['project-'+unit.id]:'today'},drafts:{[unit.id]:{text:'done'}},attempts:[]});assert.equal(p.attempted,0);assert.equal(p.passed,false);assert.equal(p.next,'reading');});
test('speaking requires a safe immutable recording receipt for the exact answer',()=>{const s=fixture();assert.equal(projectProgress(unit,s).spoken,true);s.attempts.find(a=>a.exerciseId==='speaking').answer='A different transcript is now submitted.';assert.equal(projectProgress(unit,s).spoken,false);assert.equal(projectAudioURL('../secret.wav'),'');assert.equal(projectAudioURL(file),'/media/'+file);});
test('revision binds to current artifacts and seven-day transfer cannot be brought forward',()=>{const s=fixture();revise(s);let p=projectProgress(unit,s,Date.parse('2026-01-08T10:00:00Z'));assert.equal(p.revised,true);assert.equal(p.due,false);transfer(s,'2026-01-08T10:00:00Z');assert.equal(projectProgress(unit,s).transferred,false);s.attempts.pop();transfer(s);assert.equal(projectProgress(unit,s).passed,true);s.attempts.push({...s.attempts[0],id:'new-reading',at:'2026-01-10T10:00:00Z'});assert.equal(projectProgress(unit,s).revised,false);assert.equal(projectProgress(unit,s).passed,false);});
test('offline references and partial feedback never become a positive assessment',()=>{for(const [source,verdict] of [['reference','ungraded'],['reference','correct'],['codex','partial']]){const s=fixture(source,verdict);revise(s);transfer(s);const p=projectProgress(unit,s);assert.equal(p.transferred,true);assert.equal(p.passed,false);}});
test('model and listening-transcript support remain visible in evidence',()=>{const s=fixture();revise(s);transfer(s);assert.equal(projectProgress(unit,s).independent,true);s.drafts[projectReceiptKey('conditions',unit.id,'try-listening')]={text:JSON.stringify({transcript:true})};assert.equal(projectProgress(unit,s).supported,true);assert.equal(projectProgress(unit,s).independent,false);});
test('unsorted imports use the latest valid time; future and malformed dates cannot unlock work',()=>{const now=Date.parse('2026-01-10T12:00:00Z'),s=fixture();const old={...s.attempts[0],id:'older-wrong',at:'2025-12-31T10:00:00Z',feedback:{source:'codex',verdict:'incorrect'}};s.attempts.push(old);assert.equal(projectProgress(unit,s,now).attempts[0].id,'try-reading');s.attempts.unshift({...old,id:'newer-wrong',at:'2026-01-02T11:00:00Z'});assert.equal(projectProgress(unit,s,now).attempts[0].id,'newer-wrong');assert.equal(projectProgress(unit,s,now).needsWork,true);s.attempts.push({...old,id:'future-correct',at:'2027-01-01T00:00:00Z',feedback:{source:'codex',verdict:'correct'}},{...old,id:'invalid-correct',at:'2026-02-31T00:00:00Z',feedback:{source:'codex',verdict:'correct'}});assert.equal(projectProgress(unit,s,now).attempts[0].id,'newer-wrong');const futureOnly=fixture();futureOnly.attempts=futureOnly.attempts.map(a=>({...a,at:'2027-01-01T00:00:00Z'}));assert.equal(projectProgress(unit,futureOnly,now).attempted,0);assert.equal(projectProgress(unit,futureOnly,now).passed,false);assert.equal(projectProgress(unit,futureOnly,now).due,false);});
test('a backdated revision and a future transfer cannot create completed evidence',()=>{const s=fixture();revise(s);s.attempts.find(a=>a.exerciseId==='revision').at='2025-12-31T10:00:00Z';assert.equal(projectProgress(unit,s).revised,false);s.attempts.find(a=>a.exerciseId==='revision').at='2026-01-02T10:00:00Z';transfer(s,'2099-01-09T10:00:00Z');const p=projectProgress(unit,s,Date.parse('2026-01-10T00:00:00Z'));assert.equal(p.revised,true);assert.equal(p.transferred,false);assert.equal(p.passed,false);});
test('each level has two distinct projects and checkpoint forms with real sources and transfer',()=>{assert.equal(catalog.units.length,24);const texts=new Set(),prompts=new Set();for(const level of ['A1','A2','B1','B2','C1','C2'])for(const kind of ['project','checkpoint'])assert.equal(catalog.units.filter(u=>u.level===level&&u.kind===kind).length,2);for(const u of catalog.units){assert.deepEqual(u.tasks.map(t=>t.kind),['reading','listening','writing','speaking','mediation']);for(const m of u.materials){assert.ok(m.text.length>200);assert.ok(!texts.has(m.text));texts.add(m.text);}for(const t of u.tasks){assert.ok(t.model.length>35);assert.ok(t.explanation.length>50);assert.ok(!prompts.has(t.prompt));prompts.add(t.prompt);assert.ok(t.materialIds.every(id=>u.materials.some(m=>m.id===id)));}assert.equal(u.transfer.delayDays,7);assert.ok(!prompts.has(u.transfer.prompt));assert.ok(u.reflectionPrompt.length>80);}});
