"""Editorially authored B2 additions. No model calls or public course writes.

The two specifications and their private caches are validated before any write.
The main plan and the final release are owned by the course publisher.
"""
from pathlib import Path
import hashlib
import json
import re
from build_extended_course import validate, validate_plan, digest, VERSION, stamp, words
from publish_book_release import atomic_json

APP = Path(__file__).resolve().parents[1]

SOURCES = [
 dict(id='b2-wishes-bc', title='British Council: Wishes — wish and if only', url='https://learnenglish.britishcouncil.org/free-resources/grammar/b1-b2/wishes-wish-if-only', checkedAt='2026-09-10', use='Present unreal wishes, past regret, emotional force; no publisher exercise copied.'),
 dict(id='b2-emphasis-cambridge', title='Cambridge Dictionary: do, auxiliary for emphasis', url='https://dictionary.cambridge.org/us/dictionary/english/do', checkedAt='2026-09-10', use='Emphatic auxiliary do/does/did; original contrastive examples.'),
 dict(id='b2-regrets-bc', title='British Council TeachingEnglish: Regrets', url='https://www.teachingenglish.org.uk/teaching-resources/teaching-adults/activities/intermediate-b1/regrets', checkedAt='2026-09-10', use='Should have in retrospective evaluation; original lesson and tasks.'),
 dict(id='b2-sleep-nhs', title='NHS Every Mind Matters: Sleep problems', url='https://www.nhs.uk/every-mind-matters/mental-health-issues/sleep/', checkedAt='2026-09-10', use='General sleep habits can help; individual needs differ. Not a cure claim.'),
 dict(id='b2-insomnia-nhs', title='NHS: Insomnia', url='https://www.nhs.uk/conditions/insomnia/', checkedAt='2026-09-10', use='Regular sleep difficulties, daytime impact, reasons to consult a GP; no diagnosis or medicine advice.'),
 dict(id='b2-sleepiness-nhs', title='NHS: Excessive daytime sleepiness', url='https://www.nhs.uk/conditions/excessive-daytime-sleepiness-hypersomnia/', checkedAt='2026-09-10', use='Repeated daytime falling asleep differs from tiredness; appropriate GP discussion.'),
 dict(id='b2-snoring-nhs', title='NHS: Snoring', url='https://www.nhs.uk/symptoms/snoring/', checkedAt='2026-09-10', use='Snoring alone does not establish a diagnosis; report breathing interruptions and daytime sleepiness to a GP.'),
 dict(id='b2-doze-cambridge', title='Cambridge Dictionary: doze', url='https://dictionary.cambridge.org/us/dictionary/english/doze', checkedAt='2026-09-10', use='Short light sleep; original contextual examples.')
]

RULES = [
 'Все ситуации, письма и диалоги авторские и вымышленные; не копировать материал внешнего учебника.',
 'Ровно 8 заданий полного самостоятельного ответа. Нет выбора, пропусков или перестановок; полные образцы и конкретные русские разборы не менее 55 слов.',
 'Теория и примеры используют другие ситуации. Уточнение m3 доступно только начиная с e6; ранние задания и подсказки не раскрывают его фактов.',
 'Сценарная устная репетиция оценивает смысл и языковую форму; синтезированное озвучивание не является подлинной записью участников.',
 'Для темы сна медицинские сведения ограничены проверенными общедоступными страницами NHS. Никакой индивидуальной диагностики, схем лекарств или обещаний излечения.'
]

def spec_material(i, kind, title, lo, hi, brief):
 return dict(id=i,kind=kind,title=title,minWords=lo,maxWords=hi,brief=brief)

def exercise_plan(kind, ids, brief, lo, hi=None):
 return dict(kind=kind,materialIds=ids,brief=brief,minAnswerWords=lo,**({'maxAnswerWords':hi} if hi else {}))

REGRET = dict(
 id='extended-b2-regret-emphasis', level='B2', title='Если бы только: сожалеть и честно уточнять факты',
 skills=['grammar','reading','listening','speaking','writing','interaction'],
 outcomes=[
  'Различать эмоциональное желание о настоящем и сожаление о прошлом через wish и If only.',
  'Оценивать конкретное прошлое решение с should have, не превращая сожаление в доказанный факт.',
  'Уточнять оспоренный факт полными усилительными do, does и did с начальной формой глагола.',
  'Пересматривать объяснение события после нового сообщения, сохраняя подтверждённые факты и границы знания.'
 ],
 scenario='Команда обсуждает задержку открытия вымышленной фотовыставки. Сначала доступны разговор и личная история; позднее письмо меняет основание обвинения. Материал m3 появляется только в e6.',
 materials=[
  spec_material('m1','dialogue','Разговор после открытия',170,235,'Разговор команды: тесная комната сейчас, непроверенный вход вчера, сомнение в отправке карты. Мотивы и уверенность каждого названы явно; причина рассылки ещё неизвестна.'),
  spec_material('m2','reading','Запись организатора',230,310,'Связная история от лица Норы о подготовке, преждевременном обвинении и незавершённой проверке. Не раскрывать техническую причину ошибки или содержание будущего письма.'),
  spec_material('m3','listening','Позднее уточнение администратора',125,180,'Самостоятельное новое сообщение: журнал подтверждает отправку Леей правильной карты, автоматический ответ содержал старый адрес входа; сообщить ровно установленные пределы и следующий шаг.')
 ],
 exercisePlan=[
  exercise_plan('write',['m1'],'Сообщение отсутствовавшему коллеге 80–105 слов: настоящее желание, прошлое сожаление и один непроверенный вопрос.',80,105),
  exercise_plan('translate',['m1'],'Перевести полное русское сообщение с настоящим и прошлым If only/wish и should have, без добавления новых фактов.',45),
  exercise_plan('rewrite',['m1','m2'],'Переписать полный ошибочный английский текст в 80–105 слов, исправив временные формы и недоказанное обвинение.',80,105),
  exercise_plan('speak',['m1','m2'],'Монолог Норы 110–140 слов: сожаления, личная ответственность, известное и неизвестное, следующий шаг.',110,140),
  exercise_plan('write',['m1','m2'],'Ответ на три конкретных возражения 90–115 слов с полными усилительными do, does, did.',90,115),
  exercise_plan('write',['m1','m2','m3'],'Коррекция прежнего обвинения 85–110 слов по новой записи, извинение и предел установленного.',85,110),
  exercise_plan('speak',['m1','m2','m3'],'Итоговый брифинг 120–150 слов с настоящим и прошлым сожалением, should have и двумя полными усилительными утверждениями.',120,150),
  exercise_plan('rewrite',['m1','m2','m3'],'Переработать предоставленный ошибочный отчёт в 95–120 слов, сохранив доказанные факты и убрав всеобщее обвинение.',95,120)
 ],
 sourceIds=['b2-wishes-bc','b2-emphasis-cambridge','b2-regrets-bc'],
 relatedLessonIds=['grammar-intermediate-040','grammar-intermediate-041','grammar-intermediate-033','grammar-intermediate-051'],
 externalCrosswalkBlocks=['speakout-b2/3D','speakout-b2/7B'], authoringRules=RULES
)

SLEEP = dict(
 id='extended-b2-sleep', level='B2', title='О сне без громких обещаний: читать, уточнять, объяснять',
 skills=['vocabulary','reading','listening','writing','speaking','mediation'],
 outcomes=[
  'Точно описывать сон и пробуждение с sleep, fall asleep, wake up, get up, doze и snore.',
  'Различать описания insomnia, усталости и daytime sleepiness, не делать собственного диагноза.',
  'Сопоставлять осторожную рекомендацию с бездоказательным обещанием по данному тексту.',
  'Создавать понятный письменный и устный ответ, пересматривая его при поступлении новых сведений.'
 ],
 scenario='Редакция вымышленного клубного бюллетеня готовит заметку о языке сна. Авторская статья, обсуждение двух черновиков и последующее сообщение читателя дают все необходимые сведения; медицинские факты сверены с NHS.',
 materials=[
  spec_material('m1','reading','Sleep: describe the experience first',280,365,'Оригинальная статья: слова и различия, вымышленный пример, ограниченные общие сведения NHS. Не приводить будущие симптомы читателя m3.'),
  spec_material('m2','dialogue','Какой тон подходит бюллетеню',180,250,'Полный редакционный разговор с двумя краткими проектами рекомендации: абсолютное обещание и осторожная альтернатива. Не просить выбрать букву; сравнение самостоятельным текстом.'),
  spec_material('m3','listening','Уточнение читателя',115,175,'Новое вымышленное сообщение: человек уточняет разницу между усталостью и частым непроизвольным засыпанием; партнёр замечал остановки дыхания и храп. Персонаж не имеет диагноза; ранние материалы не раскрывают его ситуацию.')
 ],
 exercisePlan=[
  exercise_plan('write',['m1'],'Пояснение статьи 85–110 слов: две лексические границы и осторожное описание insomnia.',85,110),
  exercise_plan('translate',['m1'],'Перевод связного русского рассказа о ночи и следующем дне с пятью точными словосочетаниями; данные явно заданы.',45),
  exercise_plan('rewrite',['m1'],'Исправить полный английский абзац в 75–100 слов, сохраняя заданные события и различая asleep/sleep/wake/get up/doze.',75,100),
  exercise_plan('speak',['m1','m2'],'Сравнить две редакционные позиции за 110–140 слов: конкретное предложение, обещание и граница доказательств.',110,140),
  exercise_plan('write',['m1','m2'],'Самостоятельная заметка 125–155 слов для клуба с названием, лексическим примером и осторожным языком рекомендаций.',125,155),
  exercise_plan('write',['m1','m2','m3'],'Личный ответ читателю 85–115 слов, отразив новые факты и уместное обращение к GP без диагноза.',85,115),
  exercise_plan('speak',['m1','m2','m3'],'Репетиция сообщения для GP от лица читателя, 120–150 слов: наблюдения, источник сведений, неизвестное и два вопроса.',120,150),
  exercise_plan('rewrite',['m1','m2','m3'],'Переписать полный некорректный редакционный ответ в 100–125 слов, убрав гарантии, диагноз и подмену симптомов.',100,125)
 ],
 sourceIds=['b2-sleep-nhs','b2-insomnia-nhs','b2-sleepiness-nhs','b2-snoring-nhs','b2-doze-cambridge'],
 relatedLessonIds=[], externalCrosswalkBlocks=['speakout-b2/4B'], authoringRules=RULES
)

def section(title, body): return dict(title=title,body=body)
def example(en, ru, why): return dict(en=en,ru=ru,why=why)
def material(i, kind, title, text):
 return dict(id=i,kind=kind,title=title,text=text,source='Авторский учебный материал; персонажи и события вымышлены. Источники общих сведений перечислены в происхождении урока.')
def task(prompt,context,hint,answer,explanation):
 return dict(prompt=prompt,context=context,hint=hint,answers=[answer],explanation=explanation)

def regret_lesson():
 sections = [
 section('Желание сейчас: прошедшая форма не равна прошлому', '''Сначала определите, что именно хочется изменить: сегодняшнее положение или уже совершённый поступок. В I wish I lived nearer the station речь идёт о нынешнем месте жительства. Форма lived показывает расстояние между действительностью и желанием, а не обязательно прошедшее время. У человека сейчас другой адрес. Если препятствие связано с возможностью, подходит could: I wish I could carry this box alone. Это не обещание суметь завтра. После wish сохраняется подлежащее: нельзя механически переводить «жаль, что» и терять того, кому относится действие. Отрицание выбирают по желаемой картине: I wish the room wasn't so noisy означает, что шум мешает сейчас. С be возможны were и, особенно в разговорной речи при единственном числе, was. Were удобно для более нейтральной учебной формулировки, но was нельзя объявлять безусловной ошибкой. Прочитав свою фразу, назовите по-русски реальное положение: так легче заметить случайно перевёрнутое отрицание.'''),
 section('If only: эмоциональная сила и самостоятельная реплика', '''If only помогает выразить сильное желание или сожаление. Сочетание может открывать самостоятельную эмоциональную реплику: If only this suitcase were lighter! Продолжение с результатом возможно, однако оно не обязательно для законченного высказывания в разговоре. Здесь only усиливает желание, а не ограничивает количество чемоданов. Сравните обычное условие If only one passenger arrives, we can use a smaller car: речь о единственном пассажире, без сожаления. Различие определяется смыслом всей конструкции, а не соседством двух слов. Для настоящего используйте ту же нереальную прошедшую форму, что после wish; для прошлого понадобится had с причастием. В спокойном рабочем письме несколько эмоциональных восклицаний подряд могут звучать драматично. Можно оставить одну сильную реплику, затем назвать факты и действие. При чтении вслух выделите only и ключевое содержательное слово, но не повышайте громкость каждого слога. Речь должна передавать отношение, сохраняя понятность для собеседника.'''),
 section('Прошлое сожаление: wish, had и should have', '''Уже завершённый эпизод требует другой временной точки. I wish I had backed up the document выражает сожаление о том, что копию раньше не сделали. Had относится к вспомогательной части, а backed up остаётся причастием. If only I hadn't pressed that button выражает желание отменить состоявшееся нажатие. Русское «если бы я не нажал» легко провоцирует простую прошедшую форму; сначала проверьте, завершено ли событие. Should have checked оценивает прошлое решение: проверить было бы разумно. В контексте признанной ошибки такая оценка обычно подразумевает, что нужной проверки не произошло. Однако should have имеет и другие значения, например ожидание в The parcel should have arrived by now; нельзя объявлять любой пример сожалением или доказательством отсутствия доставки. В личном разборе различайте эмоциональное I wish и практическое I should have: первое показывает переживание, второе формулирует более удачное действие. Ни одна конструкция сама по себе не доказывает, кто виноват в неизвестном событии.'''),
 section('Полные do, does, did: подтвердить именно оспоренный факт', '''В утвердительной фразе вспомогательный do может подчёркивать истинность действия. I do understand the instructions уместно, когда кто-то сомневается в понимании. При he, she, it в настоящем нужен does: She does keep the receipts. Для прошлого используйте did: They did lock the cupboard. После каждой из этих форм смысловой глагол имеет начальную форму без to: не does keeps и не did locked. Утверждение сохраняет обычный порядок подлежащего и сказуемого; Do they lock it? уже вопрос. Короткое Yes, they did тоже подтверждает действие, но здесь тренируется полная фраза, понятная без восстановления пропущенного глагола. Если в предложении уже есть be, модальный или вспомогательный have, обычно усиливают его: He IS ready, She CAN explain, They HAVE replied. Не добавляйте do в He does is ready. Выделение нужно там, где существует сомнение или контраст, иначе каждое предложение начинает звучать как возражение. Не путайте усилительное do с обычным do the work, называющим само действие.'''),
 section('Сожаление не даёт права додумывать причины', '''Когда рассказчик расстроен, он часто объединяет наблюдение и объяснение. The package arrived late — наблюдаемый результат; the assistant ignored us — предположение о чужом поведении, если подтверждения нет. Для точного пересказа полезны says, according to, seems и we haven't checked yet. Они не делают речь слабой: они показывают, кому принадлежит информация и насколько она проверена. Можно уверенно признать собственный поступок, не обвиняя другого: I should have asked for confirmation before complaining. Усилительный did тоже не создаёт доказательств; его нельзя использовать для уверенного утверждения лишь потому, что так убедительнее звучит. Если позднее появляется документ, пересмотрите ту часть рассказа, которую он действительно меняет. Новый факт не обязан отменять все прежние трудности. Сначала назовите старое предположение, затем подтверждение и уточнённый вывод. Вместо безличного mistakes were made лучше прямо признать своё проверяемое действие. Это помогает отделить ответственность за слова от неизвестной ответственности за причину события.'''),
 section('Как собрать развёрнутый ответ и сохранить естественную речь', '''Полный ответ можно построить из четырёх смысловых шагов: что произошло, что хотелось бы изменить, что точно известно и что делать дальше. Не нужно превращать каждый шаг в одну и ту же грамматическую формулу. Сначала выберите время каждого сожаления, затем добавьте один уместный контраст с do, does или did. В письменном ответе местоимения должны ясно указывать на людей: после двух женских имён повтор имени иногда полезнее очередного she. В устном ответе сделайте короткую паузу перед исправлением и выделите вспомогательный глагол; спокойная интонация помогает не превратить уточнение в ссору. Образец показывает один возможный порядок мыслей, но другие точные пересказы и естественные парафразы также подходят. Проверьте, что причины взяты из доступного сообщения, а не добавлены ради красивой истории. Сожаление может завершаться реальным следующим шагом, однако обещание изменить ситуацию нельзя выдавать за уже выполненное действие. Отдельно перечитайте отрицания: они часто меняют смысл сильнее, чем выбор синонима.''')
 ]
 examples = [
 example('I wish my desk faced the window; this corner feels rather dark.', 'Мне хотелось бы, чтобы мой стол стоял лицом к окну: в этом углу довольно темно.', 'Faced относится к желаемому расположению сейчас. Рассказчик не описывает прежний кабинет; реальное положение стола его не устраивает.'),
 example('If only I could explain the joke without making it even less funny!', 'Если бы только я мог объяснить шутку и не сделать её ещё менее смешной!', 'Самостоятельная реплика выражает сильное желание иметь возможность. Условное продолжение для завершённости не требуется.'),
 example('If only I had saved a second copy before replacing the file.', 'Если бы только я сохранил вторую копию, прежде чем заменить файл.', 'Had saved относится к несостоявшемуся действию до уже совершённой замены. Пример не сообщает о нынешней привычке сохранять файлы.'),
 example('I should have asked which entrance to use before setting off.', 'Мне стоило спросить, каким входом пользоваться, прежде чем отправиться.', 'Ретроспективная оценка конкретного решения: теперь человек видит более разумное действие. Это не приказ собеседнику в настоящем.'),
 example('I do enjoy working with you; I just need a quieter place today.', 'Мне действительно нравится работать с тобой; просто сегодня мне нужно более тихое место.', 'Do подтверждает положительное отношение, которое можно было неверно понять. После него enjoy остаётся начальной формой.'),
 example('Marta does check the figures, and yesterday she did spot a duplicate payment.', 'Марта действительно проверяет цифры, и вчера она действительно заметила повторный платёж.', 'Does подчёркивает обычное действие в настоящем, did — конкретный прошлый случай. Check и spot не получают дополнительного окончания времени.')
 ]
 materials = [
 material('m1','dialogue','После открытия: разговор команды', '''Nora: I wish this room were bigger. People can see the photographs now, but there is hardly any space to talk. Yesterday was even worse. The first guests waited outside the wrong entrance for twenty minutes.

Sam: I should have checked the entrance myself. I looked at the lighting and the labels, then assumed the directions would be fine.

Nora: If only we had tested the whole journey before opening. I told two volunteers that Lea probably hadn't sent the new map. Now I'm not sure that was fair.

Sam: She says she sent it on Thursday evening. We haven't checked the message records, so we shouldn't present either version as a fact yet.

Lea: I do want to help. I'm upset about the delay too, but please ask me before deciding what I did. I can bring my sent messages tomorrow.

Sam: Nora, you said I didn't care about the visitors. I do care. I spent yesterday evening helping the people who arrived late find their photographs.

Nora: You're right. You did help them. I wish I were less quick to blame people. Let's check the records together before writing our report.'''),
 material('m2','reading','Нора: что я знала, а что предположила', '''I organised the exhibition because I wanted our neighbours to see one another differently. Each photographer chose an ordinary local place and explained why it mattered. The room was smaller than I had hoped, but the pictures looked good and the team had worked carefully on the labels.

On Friday afternoon, I received a call from a guest standing outside a locked door. Several other visitors were waiting there too. I went out to find them. The exhibition itself opened on time inside, but this group missed the opening talk because they reached the wrong entrance. They waited for twenty minutes before we found them.

I immediately thought about the new map. Lea had agreed to send it, and I had not asked for confirmation. I told two volunteers that she probably hadn't done it. I did not know that this was true. I was turning my own uncertainty into an accusation because I felt embarrassed.

Sam spent the evening helping the late arrivals, although I had accused him of not caring. I saw him take people to the photographs they wanted to see and answer their questions. Lea later said that she had sent the map. I haven't seen the message records yet.

Today I still wish we had more space. I also wish I had checked the route before inviting everyone. Those are different regrets: one concerns the room we have now; the other concerns a decision I cannot undo. Tomorrow we will examine the records and write a careful report. I want the report to explain the delay without pretending that my first guess was evidence.'''),
 material('m3','listening','Уточнение после проверки записей', '''Hello, everyone. This is Ben from the venue office. We have now checked the records with Lea. Her message on Thursday evening contained the correct map and went to everyone on the guest list. Lea did send the new directions.

However, our automatic booking reply still named the old entrance. We know that the guests who spoke to Nora had used that reply. We cannot tell from the records whether every guest read Lea's later message. Please do not write that nobody received the new map or that everybody followed the old instructions.

The automatic reply has now been corrected. Before the next event, our office will send a test booking to Sam so that he can check the whole route. The room itself has not changed. I suggest that the report distinguish the incorrect automatic reply from the correct message Lea sent. Thank you for waiting until we had checked both.''')
 ]
 exercises = [
 task('Напиши отсутствовавшему коллеге 80–105 английских слов по разговору. Передай одно желание о настоящем и одно сожаление о прошлом; объясни, какой вопрос пока нельзя считать решённым. Используй wish и If only хотя бы по одному разу.', 'Коллега слышал только, что гости задержались. Ему нужен точный краткий пересказ m1 без преждевременного обвинения.', 'Отдели то, что участники наблюдали, от того, что ещё предстоит проверить. Сначала определи время каждого сожаления.',
 '''The team is discussing the visitors who waited at the wrong entrance for twenty minutes. Nora wishes the room were bigger because there is little space to talk. If only they had checked the whole journey before opening, the team might have noticed the problem earlier. Sam admits that he should have checked the entrance himself. Lea says she sent the new map, but the message records have not been checked yet. We should not decide that she failed to send it. The team plans to examine the records together.''',
 '''Образец связывает were bigger с нынешней комнатой, а had checked — с уже упущенной проверкой перед открытием. Might have noticed оставляет результат предположительным: разговор не доказывает, что проверка обязательно предотвратила бы задержку. Says she sent точно передаёт заявление Леи, не выдавая его за проверенную запись. Принимается другой порядок предложений и пересказ своими словами, если сохраняются двадцать минут, различие времён и незавершённость проверки. Нельзя уверенно обвинять Лею или придумывать уже найденную техническую причину.'''),
 task('Переведи всё сообщение на английский, сохранив эмоциональное If only и оценку прошлого через should have: «Если бы только у нас сейчас было больше места! Мне жаль, что мы не проверили вход до открытия. Мне стоило сначала спросить Лею, прежде чем обвинять её. Она говорит, что отправила карту, но мы пока не проверили записи. Я хочу понять, что произошло, а не выбрать виноватого».', 'Нора пишет команде после разговора m1. Переведи весь связный текст; отдельные подставленные формы не являются ответом.', 'Проверь, какое желание касается нынешних условий, а какое — упущенного действия. Указание на источник сообщения нужно сохранить.',
 '''If only we had more space now! I wish we had checked the entrance before opening. I should have asked Lea first before blaming her. She says she sent the map, but we haven't checked the records yet. I want to understand what happened, rather than choose someone to blame.''',
 '''Had more space здесь простая прошедшая форма have для нереального настоящего, а had checked содержит вспомогательное had и причастие: это сожаление о прошлом. Should have asked передаёт признание более разумного поведения без приказа другому человеку. Before blaming естественно сжимает придаточную часть, но before I blamed her также возможно. Важны says и yet: они сохраняют границу между заявлением и проверкой. Другие естественные переводы принимаются, если переданы все мысли, эмоциональность первой фразы и отсутствие окончательного обвинения.'''),
 task('Перепиши ошибочный текст в 80–105 английских слов, исправив формы и недоказанное обвинение: “Nora wishes the room is bigger now. If only she checked the route before Friday’s opening! Sam did helped the visitors, but Nora does thinks he never cares. Lea definitely forgot the map. Nora should asked her first. The exhibition opened late for everybody, so the team already knows exactly who caused everything.” Сохрани подтверждённые события m1–m2 и обозначь неизвестное.', 'Ты редактируешь внутреннюю заметку для команды. Полный исходный черновик дан в задании; нужен новый связный абзац.', 'Не ограничивайся окончаниями глаголов: проверь также охват слов everybody, definitely и exactly по истории Норы.',
 '''Nora wishes the room were bigger now. If only she had checked the route before Friday's opening! Sam did help the visitors who arrived late, and Nora now recognises that he cares. She should have asked Lea before blaming her. Lea says she sent the map, but the records have not been checked. The exhibition opened on time inside; the group at the wrong entrance missed the opening talk. The team still needs to establish what happened, so the report should not name Lea as the cause of the delay.''',
 '''Were относится к нынешнему размеру комнаты; had checked переносит сожаление к завершённой подготовке. После did правильно help, а should требует have asked для прошлой оценки. Смысловая правка не менее важна: внутри открылись вовремя, опоздала конкретная группа, поэтому late for everybody неверно. Рассказ также не устанавливает, что Лея забыла отправку. Можно иначе связать предложения, но нельзя сохранить прежнее обвинение лишь потому, что исправлены глаголы. Ответ должен показать и наблюдаемую помощь Сэма, и необходимость проверить записи.'''),
 task('Выступи от лица Норы на встрече команды: 110–140 английских слов, примерно 60–90 секунд. Объясни замысел выставки, одну свою ошибку, нынешнее желание и прошлое сожаление. Используй wish, If only и should have. Отдели известное о помощи Сэма от неизвестного об отправке карты; закончи следующим шагом.', 'Это самостоятельная устная репетиция по m1–m2. Адресаты — коллеги, которым нужно понять твою позицию и продолжить работу.', 'Признание собственного поступка может быть уверенным, даже когда общая причина события ещё неизвестна. Не превращай все предложения в извинения.',
 '''I wanted this exhibition to help our neighbours see one another differently, and I still believe the photographs do that. However, I handled the delay badly. I blamed Lea before checking her account, and I should have asked her for confirmation first. I wish the room were bigger now, so people could talk more comfortably. If only I had checked the complete route before the opening! Sam did help the late arrivals; I saw him guide them and answer questions. Lea says she sent the map, but I haven't examined the records. I cannot fairly say why the directions went wrong yet. Tomorrow I want us to check the messages together and write a report based on what we can establish.''',
 '''Ответ сначала сохраняет цель события, затем признаёт конкретное действие Норы: поспешное обвинение. Were bigger описывает нынешние условия, had checked — прошедшую подготовку, should have asked — более разумное поведение. Did help подтверждается личным наблюдением в истории, поэтому усиление обосновано. Последние предложения не приписывают Лее установленную вину. Допустим другой монолог с теми же смысловыми шагами и диапазоном. Время ориентировочное: при спокойном темпе паузы естественны. Проверка текста подтверждает языковую форму и содержание, но не измеряет качество произношения.'''),
 task('Ответь от лица Норы на три реплики нового волонтёра: “You don’t want to understand what happened”; “Sam doesn’t care about visitors”; “He didn’t help anyone on Friday”. Напиши 90–115 английских слов с полными утверждениями I do…, Sam does… и he did…; после вспомогательного глагола сохрани смысловой глагол. Подкрепи ответ деталями m1–m2 и оставь вопрос о карте открытым.', 'Волонтёр делает выводы по слухам. Тебе нужно спокойно исправить три конкретных утверждения, сохранив ответственность за собственные слова.', 'Для каждого возражения выбери настоящее или прошлое. Одних коротких Yes, he did недостаточно: адресату нужно услышать, что именно подтверждается.',
 '''I do want to understand what happened, which is why I have asked the team to check the records together. I regret blaming Lea before hearing her account. Sam does care about visitors: he said so, and his actions on Friday supported that. He did help the late arrivals find the photographs they wanted to see and answered their questions. My earlier criticism of him was unfair. These points do not settle the question about the map. Lea says she sent it, and we still need to examine the messages before deciding how the directions went wrong.''',
 '''Три полных утверждения отвечают трём разным отрицаниям: do want подтверждает нынешнее намерение Норы, does care — отношение Сэма, did help — прошлое действие. После вспомогательных форм стоят want, care и help без дополнительных окончаний. Подтверждение помощи опирается на рассказ, а отношение Сэма — на его слова и описанные действия. Другие глаголы возможны при сохранении смысла, но короткие ответы не выполняют цель этой тренировки. Последние фразы показывают, что исправление слуха о Сэме не доказывает автоматически версию об отправке карты.'''),
 task('Прослушай m3. Напиши двум волонтёрам 85–110 английских слов от лица Норы: исправь своё прежнее обвинение, передай подтверждение и причину путаницы, извинись и назови один предел проверки. Используй полное усилительное did с действием Леи.', 'Два волонтёра слышали раннее предположение Норы. Теперь им нужно получить уточнение до подготовки общего отчёта.', 'Сообщи, что изменилось в знании команды, а не только что тебе жаль. Отправка, получение и прочтение сообщения — разные утверждения.',
 '''I need to correct what I told you about Lea. She did send the correct map on Thursday evening, and the records show that her message went to everyone on the guest list. I am sorry I blamed her before checking. The venue's automatic booking reply still named the old entrance, and the guests who spoke to me had used that reply. We do not know whether every guest read Lea's later message. The office has corrected the automatic reply and will send Sam a test booking before the next event.''',
 '''Did send теперь опирается на проверенные записи, а не только на заявление Леи. Went to everyone передаёт рассылку по списку, но не превращается в everyone read it: письмо прямо оставляет чтение неизвестным. Причина путаницы названа точно — старый вход в автоматическом ответе. Извинение относится к преждевременному обвинению Норы. Принимаются другие вежливые формулировки, если не появляется утверждение о всех посетителях без исключения. Важно различать уже исправленный автоматический ответ и будущую проверочную бронь: это разные стадии работы.'''),
 task('Подготовь итоговый устный брифинг команды на 120–150 английских слов, примерно 70–100 секунд. По всем материалам назови установленную причину путаницы, одно неизвестное, настоящее желание, прошлое сожаление и урок для следующего события. Используй wish, If only, should have и два полных усилительных утверждения do/does/did.', 'После проверки команда возвращается к работе. Твой брифинг должен быть точным и спокойным, без общего обвинения всех участников.', 'Отдели уже исправленное от ещё запланированного. Эмоциональные конструкции должны относиться к разным временным точкам, а усиление — к подтверждённым фактам.',
 '''We now have a clearer account of the delay. Lea did send the correct map on Thursday evening, but the automatic booking reply still named the old entrance. The guests who spoke to Nora had followed that reply. We cannot say whether every guest read the later map. I wish we had a larger room now, because discussion is still difficult in this space. If only we had tested the complete visitor journey before opening! We should have checked the automatic reply as well as the displays. Sam does care about visitors, and his help on Friday showed that. The office has corrected the reply and will send him a test booking before the next event. Our report should recognise the team's work while explaining the specific mistake and Nora's premature accusation fairly.''',
 '''Брифинг объединяет новую причину с сохранившимся ограничением: записи не говорят, прочёл ли каждый гость позднюю карту. Wish we had относится к нынешнему помещению, If only we had tested — к прошлой проверке. Should have checked формулирует практический вывод без обещания изменить прошлое. Did send и does care — полные подтверждения с начальной формой глагола. Варианты допустимы, если указаны исправленный ответ и будущая тестовая бронь. Не нужно изображать живую дискуссию: это самостоятельная подготовка понятного монолога для конкретных слушателей.'''),
 task('Перепиши для архива полный ошибочный отчёт в 95–120 английских слов: “Lea never sent the correct map, and every visitor used the old entrance. Sam did ignored the guests. Nora wishes the room had been bigger now. If only the team checks everything last Friday! The whole exhibition opened twenty minutes late. Nobody knows why. We should have to blame Lea, and the office has already completed next time’s route test.” Используй все три материала, исправь факты и формы, сохрани полезный вывод на будущее.', 'Архивный отчёт прочитают новые организаторы. Им нужны конкретные проверенные сведения, а не эмоциональная версия событий.', 'Проверь отдельно время открытия, конкретную группу посетителей, текущую комнату, прошлую подготовку и статус будущей проверки.',
 '''Lea did send the correct map, but the venue's automatic booking reply named the old entrance. The guests who spoke to Nora had used that reply; we cannot say that every visitor did. Sam helped the late arrivals. The exhibition opened on time inside, while that group missed the opening talk after waiting twenty minutes. Nora wishes the room were bigger now. If only the team had tested the route beforehand! They should have checked the booking reply before the event. The office has corrected it and will send Sam a test booking. Nora regrets blaming Lea before examining the records.''',
 '''Новый отчёт исправляет не только did ignored, но и неверный охват утверждений. Группа ждала двадцать минут, однако выставка внутри открылась вовремя. Were bigger now согласует желание с настоящим, had tested относится к прошлому, should have checked — к оценке подготовки. Будущая тестовая бронь не объявляется уже выполненной. Усилительное did send уместно как явное исправление первого обвинения. Можно выбрать другой порядок и синонимы, сохранив все существенные факты. Не требуется буквально переносить каждое ошибочное предложение: важнее связный точный отчёт для нового читателя.''')
 ]
 return package(REGRET, sections,examples,materials,exercises,
  'wish / If only + past form → желание сейчас; + had + V3 → сожаление о прошлом; should have + V3 → оценка решения; do / does / did + base verb → уверенное уточнение.',
  'Разобрать событие, выразить сожаление и исправить обвинение после новой информации.',
  [(0,[1,2,3,4,7,8]),(2,[2,3,4,7,8]),(3,[5,6,7,8]),(4,[1,5,6,7,8])])

def sleep_lesson():
 sections = [
 section('Сон как процесс, начало и состояние', '''Русское «спать» скрывает несколько разных английских конструкций. Sleep описывает процесс или привычку: I sleep badly when the street is noisy. Fall asleep обозначает переход ко сну: I fell asleep during the film. Asleep — прилагательное состояния, поэтому нужен подходящий глагол: The baby is asleep или I was already asleep. Форма I asleep без сказуемого не работает; I am sleeping грамматически возможна как описание процесса, но не заменяет любой случай asleep. У sleep формы slept и slept, у fall — fell и fallen. Существительное sleep часто неисчисляемое: get enough sleep, a lack of sleep. Выражение a good night's sleep называет конкретный удачный ночной отдых. При пересказе выбирайте глагол по событию: время засыпания не равно общей продолжительности сна. Если человек лёг в десять, но долго читал, нельзя автоматически сообщать, что он slept from ten. Точность последовательности важнее механической замены русского слова одним английским.'''),
 section('Проснуться, встать и ненадолго задремать', '''Wake up означает перестать спать, а get up — встать с постели. Между событиями может пройти время: I woke up at six but got up at half past six. В прошедшем используются woke и got; причастие от wake — woken. Указание времени особенно важно в дневнике, где человек может проснуться ночью и снова уснуть. Doze описывает короткий лёгкий сон; doze off подчёркивает начало такого засыпания. Это не обязательно заранее запланированный отдых. Have a nap или take a nap обычно называет короткий сон как отдельный эпизод, часто намеренный, хотя контекст важнее жёсткого правила о намерении. Не приписывайте человеку полноценную ночь сна только потому, что он задремал в кресле. Различайте wake someone up и wake up yourself по объекту: The alarm woke me up показывает причину пробуждения. В связном рассказе помогают before, afterwards и while, но они должны соединять события в фактическом порядке, а не создавать новую причину.'''),
 section('Точные слова вместо поспешного диагноза', '''Tired передаёт усталость, а sleepy — желание или склонность заснуть. Человек может быть tired после нагрузки и при этом не засыпать; daytime sleepiness конкретнее говорит о сонливости днём. Важно описывать наблюдение: I kept dozing off during quiet activities точнее общего I felt bad. Snore означает храпеть; сам этот глагол не сообщает причину звука и не доказывает заболевание. Слово insomnia связано с регулярными трудностями сна, но рассказ об одной неудачной ночи не даёт основания уверенно навешивать этот ярлык на себя или другого. В разговоре можно сказать I have trouble falling asleep или I keep waking up, оставляя специалисту выяснение причины. Различайте наблюдение самого человека и сообщение другого: My partner says I snore указывает источник, а не выдаёт чужую оценку за собственное измерение. Для точного языка полезны frequency words: occasionally, several times, often. Они не взаимозаменяемы и должны соответствовать предоставленным сведениям.'''),
 section('Как читать осторожную рекомендацию', '''Сравнивая два совета, найдите действие, степень уверенности и границу применимости. Might help описывает возможность пользы; will cure everyone обещает результат для всех и требует совсем другого основания. Не подменяйте аргумент привлекательным тоном или личной историей автора. Фраза it worked for me может правдиво описывать опыт, но не устанавливает универсальный эффект. Useful first steps и a guaranteed solution различаются не украшением речи, а силой утверждения. В своих заметках отделяйте предложение изменить привычку от заявления, что причина проблемы уже известна. Осторожность не означает полное отсутствие содержания: назовите конкретное действие из статьи и объясните, почему редактор не должен обещать определённый результат. Если в источнике дан повод обратиться за дальнейшей оценкой, не заменяйте его уверенным домашним решением. Однако не нужно превращать любой повседневный рассказ в тревожное предупреждение. Задача читателя — передать ровно тот уровень определённости, который поддержан данным материалом и контекстом.'''),
 section('Пересказ статьи: факт, пример и область вывода', '''В учебной статье могут соседствовать общая информация, вымышленный пример и мнение редактора. Эти слои нужно различать в своём ответе. The article explains вводит мысль текста; in the example ограничивает вывод конкретной историей; the editor suggests обозначает предложение, а не установленное исследованием следствие. Не пишите research proves, если перед вами нет описания исследования. Для связного абзаца сначала сформулируйте основную мысль своими словами, затем приведите одну деталь и объясните её значение для адресата. Длинная переписанная цитата не заменяет понимания. Слова everyone, always и definitely требуют особенно внимательной проверки: они незаметно расширяют область утверждения. Сохраняйте и отрицательные границы: not necessarily не означает never, а may help не означает useless. В конце можно задать вопрос, на который текст не отвечает, однако нельзя придумать ответ ради завершённости. Такой пересказ полезен и вне темы сна: он помогает честно работать с любой популярной статьёй о привычках, обучении или повседневных решениях.'''),
 section('Письменный ответ и устная репетиция с новой информацией', '''Ответ конкретному человеку отличается от общей заметки. В начале подтвердите, что поняли его уточнение, затем назовите наблюдения без преувеличения и предложите следующий шаг, соответствующий сообщению. Когда появляются новые сведения, изменяйте ответ по их содержанию, а не просто добавляйте more или very к старой версии. В устной репетиции говорите от заданного лица и указывайте, что знаете лично, а что услышали от другого. Не добавляйте длительность, измерения или названия состояний, которых в сообщении нет. Два полезных вопроса должны прояснять дальнейшие действия, а не заранее предполагать диагноз. В письменной заметке название помогает читателю понять тему, но основной смысл должен оставаться понятным без него. Образцы дают один естественный способ выполнить задачу; точные парафразы и другой порядок мысли также подходят. При самопроверке отдельно проверьте значения слов, последовательность событий, тон рекомендаций и достаточность ответа для адресата. Озвучивание позволяет репетировать речь, а проверка текста не измеряет акустическое качество произношения.''')
 ]
 examples = [
 example('I fell asleep on the sofa, but I did not sleep there all night.', 'Я заснул на диване, но не проспал там всю ночь.', 'Fell asleep называет начало сна, sleep — его продолжение. Первое событие не доказывает длительность второго.'),
 example('When the alarm rang, I was already awake, but I had not got up.', 'Когда прозвенел будильник, я уже не спал, но ещё не встал.', 'Awake описывает состояние без сна, got up — отдельное действие. Фраза не противоречива: человек может лежать в постели после пробуждения.'),
 example('I dozed off in the armchair while the documentary was still playing.', 'Я задремал в кресле, пока документальный фильм ещё шёл.', 'Dozed off передаёт короткое засыпание, не утверждая, что человек заранее запланировал дневной сон или спал до утра.'),
 example('My flatmate says I sometimes snore, although I have never heard it myself.', 'Сосед по квартире говорит, что я иногда храплю, хотя сам я этого никогда не слышал.', 'Says обозначает источник наблюдения, sometimes — ограниченную частоту. Глагол snore сам по себе не является диагнозом.'),
 example('Feeling tired after a busy afternoon is not the same description as repeatedly falling asleep.', 'Чувствовать усталость после напряжённого дня — не то же описание, что неоднократно засыпать.', 'Сравниваются значения описаний, без вывода о причине состояния конкретного человека. Repeatedly нельзя заменить once без изменения смысла.'),
 example('The article suggests a possible first step; it does not promise that the problem will disappear.', 'Статья предлагает возможный первый шаг; она не обещает, что проблема исчезнет.', 'Suggests и possible ограничивают силу рекомендации. Пересказ сохраняет эту границу вместо превращения предложения в гарантию.')
 ]
 materials = [
 material('m1','reading','Sleep: describe the experience first', '''Our community newsletter often receives messages about sleep. Before comparing advice, it helps to describe the experience accurately. The words we choose can make an ordinary account clearer without pretending to explain its cause.

Imagine Mina, a fictional reader. She went to bed at eleven, read for half an hour and then fell asleep. She woke up at six but stayed in bed until half past six. Saying that she slept from eleven would miss the time she spent reading. Saying that she got up at six would also change the story. Later, she briefly dozed in an armchair. That short, light sleep was another event, not part of her night in bed.

Feeling tired and repeatedly falling asleep during the day are different descriptions. Someone may feel tired without actually dozing off. Insomnia refers to regular difficulties with sleep, such as struggling to fall asleep or stay asleep. One disappointing night is not enough information for a confident label. Similarly, snoring describes a sound during sleep; the word alone does not explain why it happens.

General NHS information suggests that a regular routine and time to relax before bed can help with sleep. It does not promise a result for every person. If someone often falls asleep during the day, or sleepiness affects their life, the NHS advises speaking to a GP. Persistent sleep difficulties that affect daily life also deserve further discussion rather than a confident guess from a newsletter.

Our job as readers is therefore practical: separate the observation, the proposed action and the strength of the claim. A story about one person's improved routine can illustrate an idea, but it cannot establish that the same change will solve everybody's problem. A useful reply begins with what the person actually said and leaves room for questions.'''),
 material('m2','dialogue','Два черновика для бюллетеня', '''Editor: We need a short paragraph for next week's newsletter. Here is the first draft: "Go to bed at exactly ten every evening and your sleep problems will disappear within three days. My cousin tried it, so we know it works for everybody. If you still feel tired, you simply haven't followed the routine properly."

Writer: That sounds confident, but the example doesn't support those promises. We don't know the readers' situations, and blaming them would be unfair. The article distinguishes tiredness from actually falling asleep.

Editor: Here is the second draft: "You could try keeping a regular routine and allowing some quiet time before bed. These are possible first steps, not a promise of a particular result. Describe what happens during the night and day, and seek further advice when the problem continues or affects daily life."

Writer: That version gives a concrete suggestion while admitting its limits. I would keep the distinction between waking up and getting up too. Readers can use those words to explain their experience more accurately.

Editor: Agreed. Let's explain our reasoning instead of simply announcing that one paragraph sounds nicer. We should not turn this newsletter into a diagnosis or imply that every reader has the same problem.'''),
 material('m3','listening','Сообщение читателя после статьи', '''Hello, this is Jon. I read your newsletter and realised that my first message was too vague. I wrote that I felt tired after work, but I often fall asleep without planning to. Last week I dozed off twice while reading documents at my desk, and I missed part of a quiet meeting on another day because I fell asleep. It is starting to affect my work.

My partner also says that I snore and that my breathing sometimes seems to stop and start while I am asleep. I don't know why this happens, and I haven't discussed it with a GP yet. I haven't measured how long the interruptions last. Could you help me describe the problem clearly, rather than tell me which condition I have? I would like to know what information to bring to a conversation with a GP.''')
 ]
 exercises = [
 task('Напиши другу 85–110 английских слов по статье. Объясни различие fall asleep / sleep и wake up / get up на её примере; добавь, почему слово insomnia нельзя уверенно выводить из одной плохой ночи. Заверши одной мыслью о том, как читать обещания результата.', 'Друг хочет пересказать статью и путает разные события ночи Мины. Ему нужно понятное объяснение своими словами.', 'Сначала восстанови хронологию, затем объясни, какое утверждение выходит за пределы приведённого примера.',
 '''The article separates falling asleep from the period spent sleeping. Mina went to bed at eleven, but she read for half an hour before she fell asleep. She woke up at six and got up half an hour later, so waking and leaving bed were separate events. Insomnia concerns regular sleep difficulties; one bad night does not give us enough information to label someone's experience confidently. The article also asks us to examine promises carefully. One person's successful routine cannot show that the same change will solve everyone's problem.''',
 '''Ответ сохраняет получасовое чтение и получасовой промежуток после пробуждения: время в постели не превращается автоматически во время сна. Falling asleep обозначает переход, sleeping — процесс. Формулировка про insomnia ограничена достаточностью сведений, а не утверждает, будто серьёзные трудности всегда можно игнорировать. Последняя мысль отделяет частную историю от общего обещания. Допустимы другие точные объяснения и порядок предложений; важно не изменить время событий и не приписать статье исследование, диагноз Мины или гарантированный результат изменения привычек.'''),
 task('Переведи весь рассказ: «Вчера я лёг в одиннадцать, но заснул только в половине двенадцатого. Я проснулся в шесть и встал в половине седьмого. Днём я ненадолго задремал в кресле. Сосед говорит, что я иногда храплю. Это описание одной ночи и следующего дня, а не объяснение причины». Используй разные выражения для засыпания, пробуждения и подъёма.', 'Это заданная вымышленная запись для языковой практики. Передай все события и ограничение рассказа, сохранив источник наблюдения о храпе.', 'Английский рассказ должен различать действие и состояние. Не потеряй слово «говорит», когда передаёшь наблюдение соседа.',
 '''Yesterday I went to bed at eleven, but I didn't fall asleep until half past eleven. I woke up at six and got up at half past six. During the day, I briefly dozed in an armchair. My flatmate says I sometimes snore. This describes one night and the following day, rather than explaining the cause.''',
 '''Didn't fall asleep until передаёт «заснул только», сохраняя момент начала сна. Woke up и got up разделяют два события, а briefly dozed описывает короткий сон днём. Flatmate подходит для соседа по квартире; neighbour допустим, если контекст общего проживания не подразумевается, поскольку русский исходник не уточняет тип соседства. Says и sometimes сохраняют источник и частоту. Принимаются естественные варианты времени и связок, но нельзя добавлять длительную проблему, медицинский вывод или утверждение, что рассказчик сам слышал свой храп.'''),
 task('Исправь и расширь до 75–100 английских слов полный абзац, сохранив только заданные факты: “Mina asleep at half past eleven after reading. She sleeped until six. She got up at six but stayed in bed until half past six. Later she woke in an armchair for a short light sleep. These times prove why she is tired.” По статье различи события и убери неподтверждённый вывод о причине.', 'Ты редактируешь пересказ истории Мины для учебной заметки. Читателю нужна связная хронология с объяснением хотя бы одной исправленной неточности.', 'Для каждого времени реши, начался ли сон, закончился ли он или человек встал. Короткий сон в кресле нельзя назвать пробуждением.',
 '''Mina fell asleep at half past eleven after reading for half an hour. She slept until six, when she woke up. However, she did not get up until half past six. Those are different events: she was awake in bed for thirty minutes. Later, she briefly dozed in an armchair, which means she had a short, light sleep. The account describes when these things happened. It does not establish why she might feel tired or identify a medical cause.''',
 '''Fell asleep исправляет отсутствие глагола перед asleep, а slept заменяет неправильную форму sleeped. Исходное got up at six противоречило оставанию в постели, поэтому ответ разделяет пробуждение и подъём. Dozed соответствует короткому лёгкому сну в кресле; woke означало бы его окончание. Заключение убирает причинный вывод, которого история не поддерживает. Другой связный пересказ принимается, если все времена сохранены и хотя бы одно различие объяснено читателю. Не нужно вводить диагноз, качество ночи или дополнительные пробуждения, о которых статья не сообщает.'''),
 task('После m2 объясни редактору устно, чем отличаются два черновика: 110–140 английских слов, примерно 60–90 секунд. Назови одно неподтверждённое обещание, объясни ограничение истории о родственнике, предложи сохранить конкретную осторожную рекомендацию и одну полезную лексическую границу из статьи.', 'Это самостоятельная репетиция редакционного обсуждения. Не отвечай только «первый плохой, второй хороший»: редактору нужны причины и пригодная для заметки мысль.', 'Сравни не приятность тона, а силу утверждения и основание. Отдельно назови, что читатель сможет сделать или описать точнее.',
 '''The first draft promises that everyone's sleep problems will disappear within three days. The story about one cousin cannot support that claim, and the paragraph unfairly blames readers if they remain tired. We do not know that they all have the same experience. I would keep the second draft's suggestion of a regular routine and quiet time before bed, while making clear that these are possible first steps. It offers an action without guaranteeing a result. I would also explain the difference between waking up and getting up. Someone may be awake but still in bed, so those expressions help readers give a more accurate account. The newsletter should support clear description and appropriate questions rather than announce a diagnosis.''',
 '''Монолог выделяет проверяемый недостаток первого текста: обещание трёхдневного результата для всех не следует из истории об одном родственнике. Предлагаемое действие во втором черновике сохранено вместе с ограничением, поэтому осторожность не превращается в пустую фразу. Waking up и getting up дают читателю конкретный языковой инструмент. Допустимо иначе сформулировать редакционное предложение, если сохранены все четыре требуемые части. Не стоит добавлять новые методы, сроки эффекта или причины состояния читателей: они не нужны для сравнения предоставленных черновиков.'''),
 task('Напиши самостоятельную заметку для клуба: 125–155 английских слов вместе с коротким названием. По m1–m2 дай пример различия двух событий сна, используй doze, snore и insomnia в понятном контексте и предложи одну осторожную привычку из текста. Объясни, почему частная история не даёт гарантии всем; не ставь диагноз читателю.', 'Твоя заметка должна быть понятна человеку, который не видел редакционный разговор. Нужен цельный готовый текст, а не план будущей статьи.', 'Распредели слова между примером, пояснением и рекомендацией. Для серьёзного утверждения о причине нужен источник, которого личная история сама по себе не даёт.',
 '''Talking Clearly About Sleep

Going to bed, falling asleep and waking up are not the same event. You might wake up at six but remain in bed until half past six. If you later doze in an armchair, that is a separate short, light sleep. Saying that you snore describes something that happens during sleep; it does not explain the cause. Likewise, one bad night is not enough information to confidently label an experience as insomnia.

A regular routine and some quiet time before bed may be useful first steps, but they are not a guarantee. A relative's successful experience can illustrate an idea without proving it will work for everyone. Describe what happens, how often it happens and how it affects your day. Clear observations make a conversation more useful than a confident guess.''',
 '''Заметка понятна без диалога: пример сначала разделяет пробуждение и подъём, затем отдельно объясняет doze. Snore описывает явление без установленной причины, а insomnia не навешивается на читателя по одному эпизоду. Рекомендация передана через may и first steps, а не как гарантированный эффект. Заголовок включён в общий объём. Возможны другие простые примеры и организация текста, если все три целевых слова встроены осмысленно. Не следует приписывать NHS вымышленную семейную историю или расширять её до доказательства для каждого человека.'''),
 task('Прослушай уточнение Джона в m3. Ответь ему письменно в 85–115 английских слов: покажи, чем новые сведения отличаются от прежнего «устал после работы», предложи обсудить их с GP и назови, что полезно передать из его сообщения. Сохрани неопределённость причины и источник наблюдения о дыхании.', 'Ты отвечаешь как редактор бюллетеня, помогающий понятно изложить наблюдения. Джон просит поддержку в подготовке разговора, а не название болезни.', 'Отдели события, которые Джон пережил сам, от слов его партнёра. Не превращай частоту из сообщения в придуманную длительность проблемы.',
 '''Thank you for explaining more clearly, Jon. You are describing unplanned daytime sleep, rather than only feeling tired after work. Please discuss this with a GP, including the effect on your work and your partner's observations about snoring and breathing interruptions. You could mention the two occasions at your desk and the meeting last week. Make clear which events you remember and which details your partner reported. Your message does not establish the cause, so I cannot name a condition. We can help you organise these observations before the conversation.''',
 '''Ответ отражает новые факты: речь теперь идёт о непреднамеренном засыпании и влиянии на работу, а не только о субъективной усталости. Обращение к GP соответствует проверенным общим рекомендациям NHS для такого описания; редактор не выбирает диагноз. Два случая у стола и встреча взяты из сообщения, а дыхательные наблюдения отнесены к партнёру. Допускается другой вежливый ответ с тем же содержанием. Нельзя придумывать месяцы симптомов, длительность остановок или уверять, что достаточно одного изменения режима: этих оснований материал не даёт.'''),
 task('Подготовь и произнеси сообщение для GP от лица Джона: 120–150 английских слов, примерно 70–100 секунд. Передай собственные события, отдельно сведения партнёра, влияние на работу и то, чего пока не знаешь. Используй daytime sleepiness или sleepy, doze и snore; задай два открытых вопроса о полезной информации и дальнейших шагах.', 'Это самостоятельная сценарная репетиция по m3. Ты готовишь понятное обращение, не изображая состоявшийся приём или ответ врача.', 'Вопросы не должны предполагать уже установленную причину. Сохрани точное число описанных эпизодов и не добавляй измерений.',
 '''I would like to discuss daytime sleepiness that is starting to affect my work. At first I described it as feeling tired after work, but I often fall asleep without planning to. Last week I dozed off twice while reading documents at my desk. On another day, I fell asleep during a quiet meeting and missed part of it. My partner says I snore and that my breathing sometimes seems to stop and start while I am asleep. Those are my partner's observations; I have not measured the interruptions myself. I do not know the cause and have not discussed this with a GP before. What information would be useful for me to record? What would you suggest as the next step in assessing this?''',
 '''Монолог последовательно отделяет личные эпизоды от наблюдения партнёра, не выдавая последнее за измерение. Twice относится только к чтению документов; встреча была отдельным случаем. Daytime sleepiness сохраняет уточнённый смысл, а не возвращает рассказ к общей усталости. Два вопроса открытые: они про сведения и дальнейшую оценку, а не про заранее выбранное заболевание. Допустимы другие формулировки и порядок, если не добавлены сроки, лечение или диагноз. Озвучивание служит репетицией обращения; качество распознавания текста не является медицинской или акустической оценкой.'''),
 task('Перепиши некорректный ответ редактора в 100–125 английских слов: “Jon, being tired and falling asleep are exactly the same. Your snoring proves you have insomnia, and we know what causes it. You slept for three hours at your desk every day last week. Your partner measured everything. Go to bed at ten and the problem will definitely disappear in three days. There is no need to discuss the new details with anyone.” По всем материалам исправь факты, тон и рекомендацию; заверши полезным предложением подготовки к разговору.', 'Этот ответ ещё не отправлен. Подготовь вместо него цельный тактичный текст для Джона, который не обещает неподтверждённый результат.', 'Проверь значения слов, число событий, неизвестные измерения и степень уверенности. Полезный следующий шаг должен вытекать из уточнённого сообщения.',
 '''Jon, thank you for clarifying what happens. Feeling tired and repeatedly falling asleep are different descriptions. You mentioned dozing off twice at your desk last week and falling asleep during a meeting on another day; you did not say that you slept there for three hours daily. Your partner reported snoring and possible breathing interruptions, but you have not measured them. These details do not establish a diagnosis of insomnia or another condition. Please discuss the daytime sleep and its effect on work with a GP. We can help you prepare a clear account of the events and distinguish your own observations from your partner's report.''',
 '''Переработка исправляет подмену tired и falling asleep, выдуманные три часа ежедневно и неподтверждённые измерения. Храп не превращается в доказательство insomnia; исходные сведения передаются как наблюдения с указанным источником. Гарантия трёхдневного результата удалена, поскольку ни статья, ни уточнение её не поддерживают. Предложение подготовить ясный рассказ полезно адресату и не заменяет дальнейшую оценку. Другие вежливые варианты принимаются, если отражают факты и пределы знания. Нельзя только смягчить definitely до probably, сохранив выдуманный диагноз или длительность: смысловые ошибки требуют полного исправления.''')
 ]
 return package(SLEEP,sections,examples,materials,exercises,
  'fall asleep → заснуть; be asleep / sleep → состояние / процесс; wake up ≠ get up; doze → задремать; наблюдение + частота + источник ≠ диагноз; may help ≠ will cure.',
  'Прочитать и пересказать статью о сне, сравнить советы и подготовить точный письменный и устный ответ.',
  [(0,[1,2,3,5]),(2,[1,5,6,7,8]),(3,[4,5,8]),(5,[4,5,6,7,8])])

def package(module,sections,examples,materials,exercises,formula,goal,coverage):
 for i,(exercise,planned) in enumerate(zip(exercises,module['exercisePlan']),1):
  exercise.update(id=f'e{i}',kind=planned['kind'],materialIds=planned['materialIds'])
 lesson=dict(id=module['id'],title=module['title'],subtitle=module['scenario'],level=module['level'],group='Полная практика навыков',units='Дополнительная программа по исследованию',minutes=75,goal=goal,formula=formula,sections=sections,examples=examples,materials=materials,exercises=exercises,generated=True,
  provenance=dict(coverage=[dict(outcome=outcome,sectionTitle=sections[index]['title'],exerciseIds=[f'e{i}' for i in ids]) for outcome,(index,ids) in zip(module['outcomes'],coverage)],warnings=[],promptVersion=VERSION,specHash=digest(module),generatedAt=stamp(),sourceIds=module['sourceIds'],relatedLessonIds=module['relatedLessonIds'],authoringMethod='editorial-manual',factCheckDate='2026-09-10',researchSources=[s for s in SOURCES if s['id'] in module['sourceIds']]))
 validate(lesson,module)
 for e,p in zip(exercises,module['exercisePlan']):
  if p.get('maxAnswerWords'):
   assert words(e['answers'][0])<=p['maxAnswerWords'],(module['id'],e['id'],'too long',words(e['answers'][0]))
 return lesson

def main():
 # Rules are already inside each module. The merger prepends top-level rules,
 # so repeating them here would invalidate the ready cache fingerprint.
 plan=dict(version=1,checkedAt='2026-09-10',status='prepared-awaiting-publisher',sources=SOURCES,authoringRules=[],modules=[REGRET,SLEEP])
 validate_plan(plan)
 lessons=[regret_lesson(),sleep_lesson()]
 # Complete validation precedes writes; no partial publication or shared-course edits.
 atomic_json(APP/'content/crosswalk-inputs/b2-regret-sleep-additions.json',plan)
 for lesson in lessons:
  path=APP/'data/extended-lessons'/f"{lesson['id']}.json"
  atomic_json(path,lesson)
  print(json.dumps(dict(id=lesson['id'],specHash=lesson['provenance']['specHash'],sha256=hashlib.sha256(path.read_bytes()).hexdigest(),theoryWords=sum(words(s['body']) for s in lesson['sections']),materials=[words(m['text']) for m in lesson['materials']],answers=[words(e['answers'][0]) for e in lesson['exercises']],explanations=[words(e['explanation']) for e in lesson['exercises']]),ensure_ascii=False))

if __name__=='__main__':main()
