"""Authored preparation for the 20 applied A1/A2 lessons beyond foundation."""
import json
from pathlib import Path

def ex(en,ru,why):return dict(en=en,ru=ru,why=why)
def task(prompt,answer,words,why):return (prompt,answer,words,why)
def guide(id,prereqs,purpose,sections,examples,tasks,before,sources):
    sections=[dict(title=a,body=b) for a,b in sections]
    practice=[]
    for i,(prompt,answer,words,why) in enumerate(tasks):
        s=sections[min(i,len(sections)-1)];e=examples[min(i,len(examples)-1)]
        practice.append(dict(id=f'prepare-{i+1}',revision=1,kind='translate',prompt=prompt,context=words,answers=[answer],hint=words,explanation=why,
            guidance=dict(title=s['title'],body=s['body']+' '+words,example=e['en'],translation=e['ru']),practiceStage='guided'))
    return dict(lessonId=id,prerequisites=prereqs,purpose=purpose,explanation=sections,examples=examples,practice=practice,beforePractice=before,sourceIds=sources)

guides=[
guide('extended-a1-registration',['path-be','path-possession','path-questions-basic','path-requests-can'],
 'Записать имя и контакт без догадок: одна короткая фраза на один факт.',
 [('Сначала имя','My name is Ann — меня зовут Энн. My — мой/моё, name — имя, is связывает имя с человеком. В анкете достаточно самого имени; полная фраза нужна в разговоре.'),
  ('Если не расслышал','Can you repeat that, please? — повторите, пожалуйста. Can you — можешь/можете, repeat — повторить, that — это, please — пожалуйста. Это готовая вежливая просьба. Не нужно угадывать цифру.'),
  ('Что уже известно','My phone number is … — мой номер телефона … . Если номер не прозвучал, поле остаётся пустым. Напиши I don’t know the number: «Я не знаю номер». Don’t know уже знакомо из Present simple.')],
 [ex('My name is Ann.','Меня зовут Энн.','My name — моё имя; is вводит это имя.'),ex('Can you repeat that, please?','Повторите это, пожалуйста.','Просим повторить, вместо того чтобы додумывать.'),ex('I don’t know the number.','Я не знаю номер.','Отрицание показывает отсутствие информации.')],
 [task('Меня зовут Сэм.','My name is Sam.','my name — моё имя; Sam — Сэм.','После my name используем is.'),
  task('Повторите это, пожалуйста.','Can you repeat that, please?','repeat — повторить; that — это; please — пожалуйста.','Can you + действие — вежливая просьба.'),
  task('Я не знаю номер.','I do not know the number.','know — знать; number — номер; do not = don’t.','Неизвестный факт лучше обозначить прямо, чем выдумать.')],
 'В основном сообщении ищи по одному факту: имя, адрес, телефон, день. Сначала записывай отдельные данные, затем объединяй только уже понятные фразы. Любые дополнительные примеры в теории не являются данными анкеты.',['a1-voa','a1-voicemail']),
guide('extended-a1-notices',['path-instructions','path-there-is','path-place-time'],
 'Прочитать короткое правило и понять, какое действие от тебя требуется.',
 [('Правило — это действие','Use the main entrance — пользуйтесь главным входом. Use — использовать, main — главный, entrance — вход. В инструкции действие стоит первым, без you.'),
  ('Можно и нельзя','You can take a small bag — можно взять маленькую сумку. Can показывает разрешение. No large bags — большие сумки нельзя: в коротком объявлении целое предложение часто сокращено.'),
  ('Время без лишних слов','The class starts at ten — занятие начинается в десять. Class — занятие, starts — начинается, at ten — в десять. Проверяй, относится ли время к нужному дню.')],
 [ex('Use the main entrance.','Пользуйтесь главным входом.','Use — действие, the main entrance — конкретный главный вход.'),ex('You can take a small bag.','Можно взять маленькую сумку.','Can + take без to.'),ex('The class starts at ten.','Занятие начинается в десять.','У class одно занятие, поэтому starts с s.')],
 [task('Пользуйтесь главным входом.','Use the main entrance.','use — пользоваться; the main entrance — главный вход.','Инструкция начинается с глагола use.'),task('Можно взять маленькую сумку.','You can take a small bag.','take — взять; small — маленький; bag — сумка.','После can не добавляем to.'),task('Занятие начинается в девять.','The class starts at nine.','class — занятие; start — начинаться; nine — девять.','Для одного занятия starts, перед точным часом at.')],
 'Сначала найди действие в каждом объявлении, затем место и время. Для своего объяснения используй отдельные короткие предложения: сначала вход, затем сумка, затем занятие.',['a1-reading']),
guide('extended-a1-chat',['path-requests-can','path-place-time','path-questions-basic'],
 'Ответить другу: согласиться, уточнить время и подтвердить встречу.',
 [('Короткое согласие','I can come — я могу прийти. I — я, can — могу, come — прийти. Этого достаточно для первого ответа. Не надо сразу описывать все планы на неделю.'),
  ('Одна точная просьба','What time? — во сколько? Полный вопрос What time can we meet? — во сколько мы можем встретиться? We — мы, meet — встретиться. Здесь can уже знакомо.'),
  ('Подтверждение','See you at three — увидимся в три. See you — готовая разговорная формула прощания перед встречей. В дружеском чате это нормально. Если время поменялось, повтори новое время.')],
 [ex('I can come on Friday.','Я могу прийти в пятницу.','On Friday — в пятницу; come не меняется после can.'),ex('What time can we meet?','Во сколько мы можем встретиться?','What time спрашивает именно время.'),ex('See you at three.','Увидимся в три.','At three подтверждает время встречи.')],
 [task('Я могу прийти в субботу.','I can come on Saturday.','come — прийти; Saturday — суббота; on — перед днём.','I can come, затем день.'),task('Во сколько мы можем встретиться?','What time can we meet?','what time — во сколько; we — мы; meet — встретиться.','Вопрос what time, затем can we.'),task('Увидимся в четыре.','See you at four.','see you — увидимся; four — четыре.','Для часа используем at.')],
 'Отдели слова собеседника от своего ответа. Сначала реши: могу прийти или нет; затем задай один вопрос; после обновления повтори новое время. Рассуждение о чате не должно подменять сам ответ другу.',['a1-invitation']),
guide('extended-a1-order',['path-articles-basic','path-countability','path-requests-can'],
 'Заказать одну вещь, добавить вторую и спокойно исправить недоразумение.',
 [('Готовая рамка заказа','Can I have a tea, please? — можно мне чай, пожалуйста? В кафе a tea значит одну порцию чая. Не нужно сначала разбирать все значения have: здесь это часть вежливого заказа.'),
  ('Два предмета','A tea and a sandwich — чай и сэндвич. And — и, соединяет позиции заказа. A перед каждым словом показывает одну порцию или один предмет.'),
  ('Исправить коротко','Tea, not coffee — чай, не кофе. Not отделяет нужную вещь от ошибочной. Sorry — извините: добавь это слово, чтобы исправление звучало мягче.')],
 [ex('Can I have a tea, please?','Можно мне чай, пожалуйста?','A tea — одна порция в ситуации заказа.'),ex('A tea and a sandwich, please.','Чай и сэндвич, пожалуйста.','And соединяет две позиции.'),ex('Sorry, tea, not coffee.','Извините, чай, не кофе.','Названы правильная и ошибочная позиции.')],
 [task('Можно мне кофе, пожалуйста?','Can I have a coffee, please?','a coffee — одна порция кофе; please — пожалуйста.','Вежливая рамка остаётся, меняется напиток.'),task('Чай и сэндвич, пожалуйста.','A tea and a sandwich, please.','tea — чай; sandwich — сэндвич; and — и.','В кафе короткий заказ естественен.'),task('Извините, чай, не кофе.','Sorry, tea, not coffee.','sorry — извините; not — не.','Понятно, какой напиток нужно заменить.')],
 'В большом диалоге сначала выбери две позиции. Затем отдельно ответь на вопрос о размере и месте. To go — с собой, for here — здесь: так часто спрашивают в американском кафе.',['a1-cafe']),
guide('extended-a1-day',['path-present-simple','path-place-time','path-adjectives-frequency'],
 'Рассказать о знакомом распорядке по одному действию за раз.',
 [('Кто делает','I start work — я начинаю работу. She starts work — она начинает работу. С she у действия появляется s. Start work — начать рабочий день, не обязательно запускать отдельную задачу.'),
  ('Когда','At eight — в восемь. I start work at eight. Для привычного действия достаточно Present simple: не нужно добавлять am перед start.'),
  ('Не всегда и не каждый день','Usually — обычно, always — всегда. I usually walk — я обычно хожу пешком. She doesn’t work on Sunday — она не работает в воскресенье: после doesn’t форма work без s.')],
 [ex('I start work at eight.','Я начинаю работу в восемь.','I + start + work + время.'),ex('She starts work at nine.','Она начинает работу в девять.','С she у starts появляется s.'),ex('She doesn’t work on Sunday.','Она не работает в воскресенье.','Doesn’t уже показывает форму, поэтому work без s.')],
 [task('Я начинаю работу в девять.','I start work at nine.','start work — начинать работу; at nine — в девять.','Привычный распорядок: I start.'),task('Она начинает работу в восемь.','She starts work at eight.','she — она; eight — восемь.','После she добавляем s к start.'),task('Она не работает в воскресенье.','She does not work on Sunday.','does not = doesn’t; Sunday — воскресенье.','После does not не добавляем s к work.')],
 'Слушай отдельно: кто, что делает, во сколько. Запиши шесть коротких событий, а не пересказ всего материала сразу. Сравнивая себя с Леей, явно меняй I на she.',['a1-voa','a1-can']),
guide('extended-a2-options',['path-comparatives','path-requests-can','path-connectors-basic'],
 'Выбрать из двух вариантов и объяснить одну причину.',
 [('Сравнение — одно отличие','This trip is cheaper — эта поездка дешевле. Cheap — дешёвый, cheaper — дешевле. Than the other trip добавляет: чем другая поездка.'),
  ('Цена не равна удобству','Cheaper сообщает о цене; shorter — о длительности. Не превращай низкую цену в вывод, что поездка удобнее во всём. Сначала назови конкретное отличие.'),
  ('Связать с собой','I prefer this trip because it is shorter — я предпочитаю эту поездку, потому что она короче. Prefer — предпочитать, because — потому что. Причина должна относиться к твоему условию.')],
 [ex('This trip is cheaper.','Эта поездка дешевле.','Сравниваем только цену.'),ex('The bus ride is shorter.','Поездка на автобусе короче.','Bus ride — поездка на автобусе, shorter — короче.'),ex('I prefer this trip because it is cheaper.','Я предпочитаю эту поездку, потому что она дешевле.','Because соединяет выбор и причину.')],
 [task('Эта поездка короче.','This trip is shorter.','trip — поездка; short → shorter — короче.','Is связывает поездку с её свойством.'),task('Поездка на автобусе дешевле.','The bus ride is cheaper.','bus ride — поездка на автобусе; cheaper — дешевле.','Названо конкретное сравнение цены.'),task('Я предпочитаю эту поездку, потому что она дешевле.','I prefer this trip because it is cheaper.','prefer — предпочитать; because — потому что; it — она, поездка.','Выбор получает одну ясную причину.')],
 'Перед основным ответом выпиши цену, длительность и ограничения каждого варианта. Если новая информация меняет выбор, напиши коротко: Now I prefer … because … . Не дополняй объявления вымышленными удобствами.',['a1-reading']),
guide('extended-a2-phone',['path-requests-can','path-future-plans','path-place-time'],
 'Назвать причину звонка и проверить новую договорённость.',
 [('Сначала цель','I’m calling about my bike — я звоню насчёт своего велосипеда. I’m calling — я сейчас звоню, about — о/насчёт, my bike — мой велосипед. Собеседник сразу понимает тему.'),
  ('Предложить время','Can I come at four? — можно прийти в четыре? Come — прийти, at four — в четыре. Чтобы изменить время, назови новое явно.'),
  ('Повторить результат','Friday at four, right? — в пятницу в четыре, верно? Right? в конце проверяет, что ты правильно понял. Не произноси старое время вместе с новым без пояснения.')],
 [ex('I’m calling about my bike.','Я звоню насчёт своего велосипеда.','About вводит тему звонка.'),ex('Can I come at four?','Можно мне прийти в четыре?','Просим подтвердить время.'),ex('Friday at four, right?','В пятницу в четыре, верно?','Коротко сверяем день и час.')],
 [task('Я звоню насчёт своего телефона.','I am calling about my phone.','I am = I’m; call — звонить; phone — телефон.','I am calling — действие сейчас.'),task('Можно мне прийти в пять?','Can I come at five?','come — прийти; five — пять.','Can I + действие.'),task('В понедельник в пять, верно?','Monday at five, right?','Monday — понедельник; right? — верно?','Повторяем условия для проверки.')],
 'Основной разговор слушай по частям: предмет звонка, проблема, новое время. Если цифру не понял, используй Can you repeat the time? — повторите время. Только потом составляй итог.',['a1-voicemail']),
guide('extended-a2-story',['path-past-simple','path-past-continuous','path-connectors-basic'],
 'Рассказать, что произошло, в понятном порядке без сложных времён.',
 [('Сначала три события','I left home. I missed the bus. I called Sam. — Я вышел из дома. Я опоздал на автобус. Я позвонил Сэму. Left — прошедшая форма leave; missed и called имеют ed.'),
  ('Порядок','First — сначала, then — затем. First I left home. Then I missed the bus. Эти слова показывают порядок. Для этого не требуется Past perfect.'),
  ('Одна причина','Because — потому что, so — поэтому. I was late, so I called Sam. Was late — опоздал; called — позвонил. Не путай событие с объяснением причины.')],
 [ex('I missed the bus.','Я опоздал на автобус.','Missed the bus означает не успел на автобус.'),ex('Then I called Sam.','Потом я позвонил Сэму.','Then показывает следующее событие.'),ex('I was late, so I called Sam.','Я опоздал, поэтому позвонил Сэму.','So вводит действие, которое стало результатом.')],
 [task('Я опоздал на автобус.','I missed the bus.','miss the bus — опоздать на автобус; miss → missed.','Past simple сообщает законченное событие.'),task('Потом я позвонил Энн.','Then I called Ann.','then — потом; call → called; Ann — Энн.','Новое событие после первого.'),task('Я опоздал, поэтому позвонил Энн.','I was late, so I called Ann.','was late — опоздал; so — поэтому.','So связывает проблему и последующее действие.')],
 'Сначала составь цепочку из отдельных событий. Затем добавь одну причину и ответ другу. Уточнение из нового сообщения должно исправить старую версию истории.',['a1-reading']),
guide('extended-a2-service',['path-past-simple','path-questions-basic','path-requests-can'],
 'Сообщить об ошибке в заказе и попросить конкретное исправление.',
 [('Что заказывал','I ordered a blue shirt — я заказал синюю рубашку. Ordered — прошедшая форма order, blue — синий, shirt — рубашка. Сначала называем заказ.'),
  ('Что получил','This shirt is red — эта рубашка красная. Два коротких предложения уже показывают проблему. Не нужны грубость, сложная жалоба или длинная предыстория.'),
  ('Что нужно сейчас','Can you send a blue one? — можете прислать синюю? One заменяет повторное shirt. Can you + send — просьба выполнить действие. Если нужен возврат денег: a refund — возврат оплаты.')],
 [ex('I ordered a blue shirt.','Я заказал синюю рубашку.','Ordered сообщает о завершённом заказе.'),ex('This shirt is red.','Эта рубашка красная.','Показываем фактическое отличие.'),ex('Can you send a blue one?','Можете прислать синюю?','One заменяет уже названную рубашку.')],
 [task('Я заказал чёрную сумку.','I ordered a black bag.','order → ordered; black — чёрный; bag — сумка.','Называем заказанную вещь.'),task('Эта сумка белая.','This bag is white.','this — эта; white — белая.','Описываем то, что получили.'),task('Можете прислать чёрную?','Can you send a black one?','send — прислать; one — уже названная сумка.','Просим конкретную замену.')],
 'В основном задании различай: твоя просьба и то, на что уже согласился сервис. Не называй возврат подтверждённым, пока оператор его не подтвердил.',['a2-apology','a1-can']),
guide('extended-a2-relay',['path-place-time','path-connectors-basic','path-future-plans'],
 'Передать другу актуальные время и место, не смешав старое сообщение с новым.',
 [('Возьми самый новый факт','The meeting is at eleven now — встреча теперь в одиннадцать. Meeting — встреча, now — теперь. Now помогает показать изменение.'),
  ('Что осталось прежним','The place is the same — место то же самое. Place — место, the same — тот же самый. Не меняй адрес, если исправили только час.'),
  ('Скажи только нужное','Meet us at the library — встречай нас у библиотеки. Meet — встреть, us — нас, library — библиотека. Другу нужен понятный план, а не отчёт о процессе чтения писем.')],
 [ex('The meeting is at eleven now.','Встреча теперь в одиннадцать.','Now отмечает обновлённое время.'),ex('The place is the same.','Место то же самое.','Отделяем изменившееся от неизменного.'),ex('Meet us at the library.','Встречай нас у библиотеки.','Короткая инструкция для друга.')],
 [task('Встреча теперь в десять.','The meeting is at ten now.','meeting — встреча; at ten — в десять; now — теперь.','Передаём новое время.'),task('Место то же самое.','The place is the same.','place — место; the same — то же самое.','Не выдумываем новую локацию.'),task('Встречай нас у музея.','Meet us at the museum.','meet — встреть; us — нас; museum — музей.','Действие и нужное место.')],
 'Прочитай первое письмо и обновление. Зачеркни только устаревшие поля в своих заметках. Затем напиши другу короткое сообщение с итоговыми данными.',['a1-invitation','a1-reading']),
guide('extended-a2-picture-description',['path-present-continuous','path-place-time','path-adjectives-frequency'],
 'Описать то, что видно на картинке, без догадок о людях.',
 [('Кто и что делает','A man is reading — мужчина читает. Man — мужчина, is reading — сейчас читает. Для действия на картинке подходит is/are + ing.'),
  ('Как его узнать','The man in a blue shirt — мужчина в синей рубашке. In здесь означает «в одежде». Эту короткую часть можно добавить к описанию действия.'),
  ('Где он','On the left — слева, on the right — справа. The man is on the left. Это положение. Само изображение не говорит, чем человек работает или что думает.')],
 [ex('A woman is reading.','Женщина читает.','Woman — женщина, is reading — действие сейчас.'),ex('The man in a blue shirt is sitting.','Мужчина в синей рубашке сидит.','In a blue shirt помогает найти человека.'),ex('The woman is on the left.','Женщина слева.','Описываем видимое положение.')],
 [task('Мужчина читает.','A man is reading.','man — мужчина; read → reading.','Is + reading показывает действие на сцене.'),task('Женщина в красной куртке стоит.','The woman in a red jacket is standing.','woman — женщина; red jacket — красная куртка; stand → standing.','Одежда определяет, о какой женщине речь.'),task('Мужчина справа.','The man is on the right.','on the right — справа.','Для положения не нужен глагол действия с ing.')],
 'Рассматривай по одному человеку. Сначала кто, затем одежда, действие и место. Формулировки «наверное, врач» и «он грустит» не заменяют видимые признаки.',['a1-reading']),
guide('extended-a2-survey-summary',['path-present-simple','path-countability','path-gerund-infinitive'],
 'Задать один понятный вопрос и точно пересказать несколько ответов.',
 [('Простой вопрос','What do you want to learn? — чему ты хочешь научиться? Want to learn — хотеть научиться. Вопрос начинается с what, затем do you.'),
  ('Передай один ответ','Sam wants to cook — Сэм хочет готовить. При переходе от I к Sam появляется wants с s. Cook — готовить. Хотеть научиться — ещё не значит уметь.'),
  ('Посчитай ответы','Three people want to cook — трое хотят готовить. People — люди, поэтому want без s. После исправления одного ответа пересчитай итоги; старое число больше не действует.')],
 [ex('What do you want to learn?','Чему ты хочешь научиться?','Вопрос о желании учиться.'),ex('Ann wants to cook.','Энн хочет готовить.','Ann — один человек, поэтому wants.'),ex('Three people want to cook.','Трое хотят готовить.','Несколько людей: want без s.')],
 [task('Чему ты хочешь научиться?','What do you want to learn?','want — хотеть; learn — учиться, научиться.','Do you ставит вопрос к want.'),task('Сэм хочет фотографировать.','Sam wants to take photos.','take photos — фотографировать; Sam — Сэм.','После wants идёт to + действие.'),task('Двое хотят готовить.','Two people want to cook.','two people — двое людей; cook — готовить.','У нескольких людей want без s.')],
 'Основной опрос разбей на шесть строк: имя, один выбор, одна причина. Сначала перескажи отдельный ответ; только затем считай группу. Не придумывай дату и цену, если их ещё нет.',['a1-can','a1-reading']),
guide('research-sound-w-v-th',['path-sound-basics','path-be','path-articles-basic'],
 'Различить четыре согласных в коротких знакомых словах.',
 [('Губы: west и vest','West — запад, vest — жилет. Для /w/ округли губы: зубы не касаются губы. Для /v/ верхние зубы у нижней губы. Сначала слушай эти два слова, затем произнеси каждое.'),
  ('Язык: thin и this','Thin — тонкий, this — этот. Для /θ/ и /ð/ кончик языка слегка касается края верхних зубов. /θ/ в thin без голоса, /ð/ в this с голосом.'),
  ('Маленькая фраза','This is a vest — это жилет. This — это, is связывает предмет с названием, a vest — один жилет. Не нужно начинать со сложного описания деревни и реки.')],
 [ex('This is a vest.','Это жилет.','В this звук /ð/, в vest звук /v/.'),ex('This is thin.','Это тонкое.','В this звонкий /ð/, в thin глухой /θ/.'),ex('We are here.','Мы здесь.','We начинается с округления губ /w/.')],
 [task('Это жилет.','This is a vest.','this — это; vest — жилет.','Is связывает this и a vest. После проверки послушай два разных согласных.'),task('Это тонкое.','This is thin.','thin — тонкий.','Прилагательному thin не нужен артикль a.'),task('Мы здесь.','We are here.','we — мы; here — здесь.','С we используем are. Начало we — /w/.')],
 'Если значки пока мешают, сначала пройди «Транскрипция с нуля», ступени 11–12. Печатный ответ не оценивает твой акцент: произнеси, запиши и сравни слова.',['a1-ipa','a1-rachel']),
guide('research-spelling-numbers',['path-questions-basic','path-requests-can','path-be'],
 'Переспросить имя или число одним коротким вопросом.',
 [('Имя по буквам','Can you spell it? — можете назвать это по буквам? Spell — произнести или написать по буквам, it — уже названное имя. Не читай буквы как звуки внутри слова: это названия букв.'),
  ('Конкретный выбор','Sixteen or sixty? — шестнадцать или шестьдесят? Or означает «или». Когда знаешь, что именно неясно, короткий выбор полезнее общего I don’t understand.'),
  ('Повтори для проверки','Is that fifteen? — это пятнадцать? Is that …? проверяет услышанное. Ответ Yes подтверждает число; No означает, что нужно исправить запись.')],
 [ex('Can you spell it?','Можете назвать это по буквам?','Spell — по буквам, it — имя.'),ex('Sixteen or sixty?','Шестнадцать или шестьдесят?','Or разделяет две услышанные версии.'),ex('Is that fifteen?','Это пятнадцать?','Проверка одной конкретной версии.')],
 [task('Можете назвать это по буквам?','Can you spell it?','spell — назвать по буквам; it — это.','Can you + spell.'),task('Четырнадцать или сорок?','Fourteen or forty?','fourteen — 14; forty — 40; or — или.','Вопрос явно называет обе версии.'),task('Это пятнадцать?','Is that fifteen?','that — это; fifteen — 15.','Is стоит первым в вопросе.')],
 'Сначала слушай отдельно пары чисел и названия букв. В основном обмене контактами записывай подтверждённые данные. Для американского названия Z используй zee.',['a1-voa','a1-voicemail']),
guide('research-ordering-checkout',['path-requests-can','path-countability','extended-a1-order'],
 'Довести простой заказ до оплаты: продукт, формат, сумма.',
 [('Одна порция','A small coffee — маленький кофе. Small стоит перед coffee. В кафе a coffee означает одну порцию; это не правило, что любое вещество всегда можно считать.'),
  ('С собой или здесь','To go — с собой, for here — здесь. Это обычные американские ответы на вопрос кассира. Добавь их после заказа: A small coffee to go, please.'),
  ('Сколько всего','How much is it? — сколько это стоит? That’s all, thanks — это всё, спасибо. Сначала закончи выбор, затем уточни сумму.')],
 [ex('A small coffee, please.','Маленький кофе, пожалуйста.','Размер перед названием.'),ex('To go, please.','С собой, пожалуйста.','Короткий ответ о формате заказа.'),ex('How much is it?','Сколько это стоит?','Вопрос о цене.')],
 [task('Маленький чай, пожалуйста.','A small tea, please.','small — маленький; tea — порция чая.','A обозначает одну порцию.'),task('С собой, пожалуйста.','To go, please.','to go — с собой.','Естественная американская фраза.'),task('Это всё, спасибо. Сколько это стоит?','That is all, thanks. How much is it?','that is all — это всё; thanks — спасибо; how much — сколько стоит.','Сначала завершение заказа, затем вопрос о сумме.')],
 'В основном диалоге не добавляй сразу пять уточнений. Скажи заказ, ответь о размере, ответь «здесь/с собой», затем проверь сумму. В примерах источника take away соответствует американскому to go.',['a1-cafe']),
guide('research-ending-s-ed',['path-present-simple','path-past-simple','path-sound-basics'],
 'Слышать, что окончание добавляет смысл, и не вставлять лишний слог.',
 [('Сначала смысл','She works — она работает, she worked — она работала. Конец слова сообщает о лице или времени. Если всегда проглатывать его, смысл может стать неясным.'),
  ('Окончание s','После /k/ в works слышно /s/; после /l/ в calls — /z/. После шипящих, например в washes, появляется слог /ɪz/. Выбор зависит от последнего звука, не последней буквы.'),
  ('Окончание ed','Worked заканчивается на /t/, called — на /d/. В wanted после /t/ добавляется слог /ɪd/. Поэтому worked не нужно читать как два слога. В быстрой речи окончания иногда ослабляются; начни с ясного образца.')],
 [ex('She works.','Она работает.','Окончание works произносится /s/.'),ex('She calls.','Она звонит.','Окончание calls произносится /z/.'),ex('I worked. I called. I wanted it.','Я работал. Я позвонил. Я хотел это.','Три окончания ed: /t/, /d/, /ɪd/.')],
 [task('Она работает.','She works.','work — работать; she — она.','С she добавь s; после проверки послушай /s/ в конце.'),task('Я позвонил.','I called.','call → called — позвонил.','После /l/ окончание ed звучит /d/, без отдельного слога.'),task('Я хотел это.','I wanted it.','want → wanted; it — это.','После /t/ в want окончание даёт дополнительный слог.')],
 'Сначала прочитай шесть слов по одному, затем фразы. При объяснении назови последний звук основы и звук окончания. Правильная расшифровка записи сама по себе не подтверждает произношение.',['a1-ed']),
guide('research-schwa-wordstress',['path-sound-basics','research-sound-w-v-th'],
 'Узнать сильный слог и не стараться произносить каждый гласный одинаково чётко.',
 [('Сильный слог','About /əˈbaʊt/: значок ˈ стоит перед сильным слогом. Громче и заметнее вторая часть, а не первая. About значит «о/об». Начни с одного слова, не с длинной фразы.'),
  ('Слабый гласный','/ə/ называется шва: короткий расслабленный звук без ударения. Он есть в начале about и в конце sofa /ˈsoʊfə/. Не читай любую букву a как одно и то же «а».'),
  ('После изменения слова проверь ударение','В photograph сильнее первый слог, в photography — второй. Это разные словарные формы. Знакомое написание не гарантирует прежнего ударения. Сначала слушай два слова, потом пробуй целую фразу.')],
 [ex('This is a sofa.','Это диван.','В sofa сильнее первый слог, последний гласный слабый.'),ex('Tell me about it.','Расскажи мне об этом.','В about ударение на втором слоге.'),ex('I like photography.','Мне нравится фотография как занятие.','В photography основной ударный слог второй.')],
 [task('Это диван.','This is a sofa.','sofa — диван.','После проверки послушай sofa и найди слабый последний слог.'),task('Расскажи мне об этом.','Tell me about it.','tell me — расскажи мне; about it — об этом.','Начало about слабое, второй слог сильный.'),task('Мне нравится фотография как занятие.','I like photography.','like — нравиться; photography — фотография как занятие.','Photography отличается по ударению от photograph.')],
 'Сначала пройди ступени 8–9 в чтении IPA. В основной практике помечай ударный слог и слушай слово; не заменяй все безударные гласные на шва по догадке.',['a1-ipa','a1-rachel']),
guide('research-telephone-messages',['path-requests-can','path-present-continuous','path-future-simple'],
 'Оставить сообщение так, чтобы человек понял, кто звонит и что нужно сделать.',
 [('Кто звонит','This is Sam — это Сэм. По телефону это обычный способ представиться. Не нужно дословно переводить русское «Сэм говорит».'),
  ('Что нужно','Please call me back — пожалуйста, перезвоните мне. Call back — перезвонить. Me — мне. Back здесь означает обратный звонок, а не место позади.'),
  ('Один следующий шаг','Can I leave a message? — можно оставить сообщение? Leave a message — готовое сочетание. Сначала попроси, затем назови имя, причину и номер.')],
 [ex('This is Ann.','Это Энн.','Так представляются по телефону.'),ex('Please call me back.','Пожалуйста, перезвоните мне.','Call back — перезвонить.'),ex('Can I leave a message?','Можно оставить сообщение?','Can I — просьба о возможности.')],
 [task('Это Сэм.','This is Sam.','this is — это; Sam — Сэм.','Телефонное представление.'),task('Пожалуйста, перезвоните мне.','Please call me back.','please — пожалуйста; call me back — перезвоните мне.','Не теряй back: оно меняет звонок на обратный.'),task('Можно оставить сообщение?','Can I leave a message?','leave a message — оставить сообщение.','После can действие без to.')],
 'Слушая длинный автоответчик, выпиши имя, причину звонка, номер и нужное действие. Необязательно понимать каждое слово, но цифры и договорённость нужно перепроверить.',['a1-voicemail']),
guide('research-apologies-remedies',['path-past-simple','path-future-simple','path-gerund-infinitive'],
 'Коротко извиниться за конкретную ошибку и сказать, как ты её исправишь.',
 [('Начни прямо','I’m sorry — извини/извините. Для опоздания I’m sorry I’m late. Late — опоздавший. Не обязательно сразу объяснять всю историю дня.'),
  ('Назови действие','I’m sorry for calling late — извини за поздний звонок. После for действие с ing: calling. Эта рамка называет конкретную ошибку.'),
  ('Предложи исправление','I’ll send the right file — я отправлю правильный файл. I’ll = I will, right здесь — правильный. Обещай то действие, которое реально можешь выполнить.')],
 [ex('I’m sorry I’m late.','Извини, что я опоздал.','Late описывает твоё состояние сейчас.'),ex('I’m sorry for calling late.','Извини за поздний звонок.','После for используем calling.'),ex('I’ll send the right file.','Я отправлю правильный файл.','Называем конкретное исправление.')],
 [task('Извини, что я опоздал.','I am sorry I am late.','I am = I’m; sorry — извини; late — опоздавший.','Прямое короткое извинение.'),task('Извини за поздний звонок.','I am sorry for calling late.','for calling — за звонок; late — поздно.','For + calling, не for call.'),task('Я отправлю правильный файл.','I will send the right file.','send — отправить; right — правильный; file — файл.','Will + send сообщает о следующем действии.')],
 'Основной ответ собери из трёх частей: извинение, короткое объяснение, исправление. Извинение не должно превращаться в обвинение собеседника.',['a2-apology']),
guide('natural-a1-welcome',['path-be','path-possession','research-spelling-numbers'],
 'Расслышать знакомство в реальной записи, начиная с одного имени.',
 [('Одна цель на прослушивание','Сначала найди только имя. My name is … — меня зовут … . Не старайся сразу пересказать весь разговор. На втором прослушивании можно проверить буквы.'),
  ('Знакомая короткая реакция','Nice to meet you — приятно познакомиться. Это готовая вежливая фраза. Nice — приятно, meet — встретить/познакомиться, you — тебя/вас. Не нужно до разговора изучать все значения nice.'),
  ('Уточни конкретное','Is that Park Street? — это Парк-стрит? Street — улица. Вопрос проверяет адрес, а не предлагает его придумать. Если не слышишь, вернись к нужному фрагменту или открой расшифровку.')],
 [ex('My name is Zoe.','Меня зовут Зои.','Сначала фраза знакомства и имя.'),ex('Nice to meet you.','Приятно познакомиться.','Готовая дружелюбная реакция.'),ex('Is that Park Street?','Это Парк-стрит?','Проверяется одна версия адреса.')],
 [task('Меня зовут Энн.','My name is Ann.','my name — моё имя; Ann — Энн.','Is соединяет фразу и имя.'),task('Приятно познакомиться.','Nice to meet you.','nice to meet you — готовая фраза знакомства.','Так отвечают при первом знакомстве.'),task('Это Пайн-стрит?','Is that Pine Street?','that — это; Pine Street — Пайн-стрит.','В вопросе is перед that.')],
 'Сначала открой именно короткий Conversation из источника и поймай имя. Затем проверь написание и адрес. Своё первое резюме можно собрать из двух уже освоенных коротких фраз.',['a1-voa'])
]

sources=[
 ('a1-voa','VOA: Lesson 1 — Welcome!','https://learningenglish.voanews.com/a/lets-learn-english-lesson-one/3111026.html','video-transcript','Прочитан официальный урок с расшифровкой знакомства. Использован принцип: имя и короткая реплика до пересказа. Примеры подготовки собственные.'),
 ('a1-can','VOA: Lesson 20 — What Can You Do?','https://learningenglish.voanews.com/a/lets-learn-english-lesson-20-what-can-you-do/3384429.html','video-transcript','Прочитан американский разговор с can/cannot и короткими уточнениями. Сверены полезные формулы, материал не скопирован.'),
 ('a1-voicemail','British Council: A voicemail message','https://learnenglish.britishcouncil.org/free-resources/listening/a1/voicemail-message','official-lesson','Прочитана расшифровка. Знакомство с ключевыми словами до аудио; имя, цифры и цель звонка извлекаются отдельно.'),
 ('a1-reading','British Council: A2 reading','https://learnenglish.britishcouncil.org/free-resources/reading/a2','official-overview','Просмотрена организация практики: подготовка, понятный источник, конкретная информация. Не источник фактов авторских вымышленных сценариев.'),
 ('a1-invitation','British Council: An invitation','https://learnenglishteens.britishcouncil.org/skills/writing/a2-writing/invitation','official-lesson','Прочитан образец короткого приглашения: понятные день и цель, короткие предложения и вопрос.'),
 ('a1-cafe','British Council: Ordering in a café','https://learnenglish.britishcouncil.org/free-resources/listening/a1/ordering-cafe','official-lesson','Прочитан диалог заказа и исправления. В наших примерах американское to go; британское take away объясняется как вариант.'),
 ('a2-apology','British Council: Apologising — A2 video worksheet','https://learnenglish.britishcouncil.org/sites/podcasts/files/LearnEnglish-Speaking-A2-Apologising.pdf','video-transcript','Прочитан открытый учебный PDF с формулами извинения и сценарием. Короткое признание ошибки до длинного объяснения.'),
 ('a1-ipa','Cambridge Dictionary: Phonetic symbols','https://dictionary.cambridge.org/help/phonetics.html','dictionary-guide','Сверены символы, ударение и различия американских словарных записей.'),
 ('a1-rachel','Rachel’s English: How to Pronounce the Schwa','https://rachelsenglish.com/english-pronounce-schwa/','video-transcript','Прочитан оригинальный авторский транскрипт о слабом гласном. Артикуляция объясняется на слове, не как русская побуквенная запись.'),
 ('a1-ed','Rachel’s English: ED endings, part 2','https://rachelsenglish.com/ed-endings-2-3/','video-transcript','Прочитан оригинальный транскрипт: правило зависит от звука, реальная связная речь меняет реализацию. Подготовка начинает с ясных отдельных слов.')
]
from beginner_replacements import attach_replacements
content_dir=Path(__file__).resolve().parents[1]/'content'
lessons=[]
for name in ['extended-skills.json','research-expansion.json','natural-listening.json']:
    lessons.extend(json.loads((content_dir/'courses'/name).read_text(encoding='utf-8')))
attach_replacements(guides,lessons)
payload=dict(version=1,sources=[dict(id=i,title=t,url=u,kind=k,notes=n) for i,t,u,k,n in sources],lessons=guides)
path=Path(__file__).resolve().parents[1]/'content'/'course-guides-a1-a2.json'
path.write_bytes((json.dumps(payload,ensure_ascii=False,indent=2)+'\n').encode('utf-8'))
print(f'{len(guides)} A1/A2 guides; {sum(len(g["practice"]) for g in guides)} preparation tasks; {sum(len(g.get("replacements",[])) for g in guides)} original tasks simplified')
